// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

pub(crate) mod expected_attribute_map_constrained {

    #[derive(Debug, Clone)]
    pub(crate) struct ExpectedAttributeMapConstrained(
        pub(crate) 
            std::collections::HashMap<::std::string::String, crate::model::ExpectedAttributeValue>,
    );

    impl crate::constrained::Constrained for ExpectedAttributeMapConstrained {
        type Unconstrained = crate::unconstrained::expected_attribute_map_unconstrained::ExpectedAttributeMapUnconstrained;
    }
    impl
        ::std::convert::From<
            ::std::collections::HashMap<
                ::std::string::String,
                crate::model::ExpectedAttributeValue,
            >,
        > for ExpectedAttributeMapConstrained
    {
        fn from(
            v: ::std::collections::HashMap<
                ::std::string::String,
                crate::model::ExpectedAttributeValue,
            >,
        ) -> Self {
            Self(v)
        }
    }

    impl ::std::convert::From<ExpectedAttributeMapConstrained>
        for ::std::collections::HashMap<::std::string::String, crate::model::ExpectedAttributeValue>
    {
        fn from(v: ExpectedAttributeMapConstrained) -> Self {
            v.0
        }
    }
}
pub(crate) mod attribute_updates_constrained {

    #[derive(Debug, Clone)]
    pub(crate) struct AttributeUpdatesConstrained(
        pub(crate) 
            std::collections::HashMap<::std::string::String, crate::model::AttributeValueUpdate>,
    );

    impl crate::constrained::Constrained for AttributeUpdatesConstrained {
        type Unconstrained =
            crate::unconstrained::attribute_updates_unconstrained::AttributeUpdatesUnconstrained;
    }
    impl
        ::std::convert::From<
            ::std::collections::HashMap<::std::string::String, crate::model::AttributeValueUpdate>,
        > for AttributeUpdatesConstrained
    {
        fn from(
            v: ::std::collections::HashMap<
                ::std::string::String,
                crate::model::AttributeValueUpdate,
            >,
        ) -> Self {
            Self(v)
        }
    }

    impl ::std::convert::From<AttributeUpdatesConstrained>
        for ::std::collections::HashMap<::std::string::String, crate::model::AttributeValueUpdate>
    {
        fn from(v: AttributeUpdatesConstrained) -> Self {
            v.0
        }
    }
}
pub(crate) mod key_schema_constrained {

    #[derive(Debug, Clone)]
    pub(crate) struct KeySchemaConstrained(
        pub(crate) std::vec::Vec<crate::model::KeySchemaElement>,
    );

    impl crate::constrained::Constrained for KeySchemaConstrained {
        type Unconstrained = crate::unconstrained::key_schema_unconstrained::KeySchemaUnconstrained;
    }
    impl ::std::convert::From<::std::vec::Vec<crate::model::KeySchemaElement>>
        for KeySchemaConstrained
    {
        fn from(v: ::std::vec::Vec<crate::model::KeySchemaElement>) -> Self {
            Self(v)
        }
    }

    impl ::std::convert::From<KeySchemaConstrained>
        for ::std::vec::Vec<crate::model::KeySchemaElement>
    {
        fn from(v: KeySchemaConstrained) -> Self {
            v.0
        }
    }
}
pub(crate) mod attribute_definitions_constrained {

    #[derive(Debug, Clone)]
    pub(crate) struct AttributeDefinitionsConstrained(
        pub(crate) std::vec::Vec<crate::model::AttributeDefinition>,
    );

    impl crate::constrained::Constrained for AttributeDefinitionsConstrained {
        type Unconstrained = crate::unconstrained::attribute_definitions_unconstrained::AttributeDefinitionsUnconstrained;
    }
    impl ::std::convert::From<::std::vec::Vec<crate::model::AttributeDefinition>>
        for AttributeDefinitionsConstrained
    {
        fn from(v: ::std::vec::Vec<crate::model::AttributeDefinition>) -> Self {
            Self(v)
        }
    }

    impl ::std::convert::From<AttributeDefinitionsConstrained>
        for ::std::vec::Vec<crate::model::AttributeDefinition>
    {
        fn from(v: AttributeDefinitionsConstrained) -> Self {
            v.0
        }
    }
}
pub(crate) mod tag_list_constrained {

    #[derive(Debug, Clone)]
    pub(crate) struct TagListConstrained(pub(crate) std::vec::Vec<crate::model::Tag>);

    impl crate::constrained::Constrained for TagListConstrained {
        type Unconstrained = crate::unconstrained::tag_list_unconstrained::TagListUnconstrained;
    }
    impl ::std::convert::From<::std::vec::Vec<crate::model::Tag>> for TagListConstrained {
        fn from(v: ::std::vec::Vec<crate::model::Tag>) -> Self {
            Self(v)
        }
    }

    impl ::std::convert::From<TagListConstrained> for ::std::vec::Vec<crate::model::Tag> {
        fn from(v: TagListConstrained) -> Self {
            v.0
        }
    }
}
pub(crate) mod global_secondary_index_list_constrained {

    #[derive(Debug, Clone)]
    pub(crate) struct GlobalSecondaryIndexListConstrained(
        pub(crate) std::vec::Vec<crate::model::GlobalSecondaryIndex>,
    );

    impl crate::constrained::Constrained for GlobalSecondaryIndexListConstrained {
        type Unconstrained = crate::unconstrained::global_secondary_index_list_unconstrained::GlobalSecondaryIndexListUnconstrained;
    }
    impl ::std::convert::From<::std::vec::Vec<crate::model::GlobalSecondaryIndex>>
        for GlobalSecondaryIndexListConstrained
    {
        fn from(v: ::std::vec::Vec<crate::model::GlobalSecondaryIndex>) -> Self {
            Self(v)
        }
    }

    impl ::std::convert::From<GlobalSecondaryIndexListConstrained>
        for ::std::vec::Vec<crate::model::GlobalSecondaryIndex>
    {
        fn from(v: GlobalSecondaryIndexListConstrained) -> Self {
            v.0
        }
    }
}
pub(crate) mod local_secondary_index_list_constrained {

    #[derive(Debug, Clone)]
    pub(crate) struct LocalSecondaryIndexListConstrained(
        pub(crate) std::vec::Vec<crate::model::LocalSecondaryIndex>,
    );

    impl crate::constrained::Constrained for LocalSecondaryIndexListConstrained {
        type Unconstrained = crate::unconstrained::local_secondary_index_list_unconstrained::LocalSecondaryIndexListUnconstrained;
    }
    impl ::std::convert::From<::std::vec::Vec<crate::model::LocalSecondaryIndex>>
        for LocalSecondaryIndexListConstrained
    {
        fn from(v: ::std::vec::Vec<crate::model::LocalSecondaryIndex>) -> Self {
            Self(v)
        }
    }

    impl ::std::convert::From<LocalSecondaryIndexListConstrained>
        for ::std::vec::Vec<crate::model::LocalSecondaryIndex>
    {
        fn from(v: LocalSecondaryIndexListConstrained) -> Self {
            v.0
        }
    }
}

/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

pub(crate) trait Constrained {
    type Unconstrained;
}

#[derive(Debug, Clone)]
#[allow(dead_code)]
pub(crate) enum MaybeConstrained<T: Constrained> {
    Constrained(T),
    Unconstrained(T::Unconstrained),
}
