// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
/// Error type for the `PutItem` operation.
/// Each variant represents an error that can occur for the `PutItem` operation.
#[derive(::std::fmt::Debug)]
pub enum PutItemError {
    /// A standard error for input validation failures. This should be thrown by services when a member of the input structure falls outside of the modeled or documented constraints.
    ValidationException(crate::error::ValidationException),
    #[allow(missing_docs)] // documentation missing in model
    InternalServerError(crate::error::InternalServerError),
    #[allow(missing_docs)] // documentation missing in model
    ProvisionedThroughputExceededException(crate::error::ProvisionedThroughputExceededException),
    #[allow(missing_docs)] // documentation missing in model
    ResourceNotFoundException(crate::error::ResourceNotFoundException),
    #[allow(missing_docs)] // documentation missing in model
    ConditionalCheckFailedException(crate::error::ConditionalCheckFailedException),
}
impl ::std::fmt::Display for PutItemError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match &self {
            PutItemError::ValidationException(_inner) =>
            _inner.fmt(f)
            ,
            PutItemError::InternalServerError(_inner) =>
            _inner.fmt(f)
            ,
            PutItemError::ProvisionedThroughputExceededException(_inner) =>
            _inner.fmt(f)
            ,
            PutItemError::ResourceNotFoundException(_inner) =>
            _inner.fmt(f)
            ,
            PutItemError::ConditionalCheckFailedException(_inner) =>
            _inner.fmt(f)
            ,
        }
    }
}
impl PutItemError {
    /// Returns `true` if the error kind is `PutItemError::ValidationException`.
    pub fn is_validation_exception(&self) -> bool {
        matches!(&self, PutItemError::ValidationException(_))
    }
    /// Returns `true` if the error kind is `PutItemError::InternalServerError`.
    pub fn is_internal_server_error(&self) -> bool {
        matches!(&self, PutItemError::InternalServerError(_))
    }
    /// Returns `true` if the error kind is `PutItemError::ProvisionedThroughputExceededException`.
    pub fn is_provisioned_throughput_exceeded_exception(&self) -> bool {
        matches!(&self, PutItemError::ProvisionedThroughputExceededException(_))
    }
    /// Returns `true` if the error kind is `PutItemError::ResourceNotFoundException`.
    pub fn is_resource_not_found_exception(&self) -> bool {
        matches!(&self, PutItemError::ResourceNotFoundException(_))
    }
    /// Returns `true` if the error kind is `PutItemError::ConditionalCheckFailedException`.
    pub fn is_conditional_check_failed_exception(&self) -> bool {
        matches!(&self, PutItemError::ConditionalCheckFailedException(_))
    }
    /// Returns the error name string by matching the correct variant.
    pub fn name(&self) -> &'static str {
        match &self {
            PutItemError::ValidationException(_inner) =>
            _inner.name()
            ,
            PutItemError::InternalServerError(_inner) =>
            _inner.name()
            ,
            PutItemError::ProvisionedThroughputExceededException(_inner) =>
            _inner.name()
            ,
            PutItemError::ResourceNotFoundException(_inner) =>
            _inner.name()
            ,
            PutItemError::ConditionalCheckFailedException(_inner) =>
            _inner.name()
            ,
        }
    }
}
impl ::std::error::Error for PutItemError {
    fn source(&self) -> std::option::Option<&(dyn ::std::error::Error + 'static)> {
        match &self {
            PutItemError::ValidationException(_inner) =>
            Some(_inner)
            ,
            PutItemError::InternalServerError(_inner) =>
            Some(_inner)
            ,
            PutItemError::ProvisionedThroughputExceededException(_inner) =>
            Some(_inner)
            ,
            PutItemError::ResourceNotFoundException(_inner) =>
            Some(_inner)
            ,
            PutItemError::ConditionalCheckFailedException(_inner) =>
            Some(_inner)
            ,
        }
    }
}
impl ::std::convert::From<crate::error::ValidationException> for crate::error::PutItemError {
    fn from(variant: crate::error::ValidationException) -> crate::error::PutItemError {
        Self::ValidationException(variant)
    }
}
impl ::std::convert::From<crate::error::InternalServerError> for crate::error::PutItemError {
    fn from(variant: crate::error::InternalServerError) -> crate::error::PutItemError {
        Self::InternalServerError(variant)
    }
}
impl ::std::convert::From<crate::error::ProvisionedThroughputExceededException> for crate::error::PutItemError {
    fn from(variant: crate::error::ProvisionedThroughputExceededException) -> crate::error::PutItemError {
        Self::ProvisionedThroughputExceededException(variant)
    }
}
impl ::std::convert::From<crate::error::ResourceNotFoundException> for crate::error::PutItemError {
    fn from(variant: crate::error::ResourceNotFoundException) -> crate::error::PutItemError {
        Self::ResourceNotFoundException(variant)
    }
}
impl ::std::convert::From<crate::error::ConditionalCheckFailedException> for crate::error::PutItemError {
    fn from(variant: crate::error::ConditionalCheckFailedException) -> crate::error::PutItemError {
        Self::ConditionalCheckFailedException(variant)
    }
}

#[allow(missing_docs)] // documentation missing in model
#[derive(::std::clone::Clone, ::std::cmp::Eq, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct ConditionalCheckFailedException  {
    #[allow(missing_docs)] // documentation missing in model
    pub message: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub item: ::std::option::Option<::std::collections::HashMap::<::std::string::String, crate::model::AttributeValue>>,
}
impl  ConditionalCheckFailedException  {
    #[allow(missing_docs)] // documentation missing in model
    pub fn item(&self) -> ::std::option::Option<&::std::collections::HashMap::<::std::string::String, crate::model::AttributeValue>> {
        self.item.as_ref()
    }
}
impl ConditionalCheckFailedException {
    /// Returns the error message.
                        pub fn message(&self) -> ::std::option::Option<&str> { self.message.as_deref() }
    #[doc(hidden)]
                        /// Returns the error name.
                        pub fn name(&self) -> &'static str {
                            "ConditionalCheckFailedException"
                        }
}
impl ::std::fmt::Display for ConditionalCheckFailedException {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        ::std::write!(f, "ConditionalCheckFailedException")?;
        if let ::std::option::Option::Some(inner_1) = &self.message {
             {
                ::std::write!(f, ": {}", inner_1)?;
            }
        }
        Ok(())
    }
}
impl ::std::error::Error for ConditionalCheckFailedException {}
impl  ConditionalCheckFailedException  {
    /// Creates a new builder-style object to manufacture [`ConditionalCheckFailedException`](crate::error::ConditionalCheckFailedException).
    pub fn builder() -> crate::error::conditional_check_failed_exception::Builder  {
        crate::error::conditional_check_failed_exception::Builder::default()
    }
}

#[allow(missing_docs)] // documentation missing in model
#[derive(::std::clone::Clone, ::std::cmp::Eq, ::std::cmp::PartialEq, ::std::fmt::Debug, ::std::hash::Hash)]
pub struct ResourceNotFoundException  {
    #[allow(missing_docs)] // documentation missing in model
    pub message: ::std::option::Option<::std::string::String>,
}
impl ResourceNotFoundException {
    /// Returns the error message.
                        pub fn message(&self) -> ::std::option::Option<&str> { self.message.as_deref() }
    #[doc(hidden)]
                        /// Returns the error name.
                        pub fn name(&self) -> &'static str {
                            "ResourceNotFoundException"
                        }
}
impl ::std::fmt::Display for ResourceNotFoundException {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        ::std::write!(f, "ResourceNotFoundException")?;
        if let ::std::option::Option::Some(inner_2) = &self.message {
             {
                ::std::write!(f, ": {}", inner_2)?;
            }
        }
        Ok(())
    }
}
impl ::std::error::Error for ResourceNotFoundException {}
impl  ResourceNotFoundException  {
    /// Creates a new builder-style object to manufacture [`ResourceNotFoundException`](crate::error::ResourceNotFoundException).
    pub fn builder() -> crate::error::resource_not_found_exception::Builder  {
        crate::error::resource_not_found_exception::Builder::default()
    }
}

#[allow(missing_docs)] // documentation missing in model
#[derive(::std::clone::Clone, ::std::cmp::Eq, ::std::cmp::PartialEq, ::std::fmt::Debug, ::std::hash::Hash)]
pub struct ProvisionedThroughputExceededException  {
    #[allow(missing_docs)] // documentation missing in model
    pub message: ::std::option::Option<::std::string::String>,
}
impl ProvisionedThroughputExceededException {
    /// Returns the error message.
                        pub fn message(&self) -> ::std::option::Option<&str> { self.message.as_deref() }
    #[doc(hidden)]
                        /// Returns the error name.
                        pub fn name(&self) -> &'static str {
                            "ProvisionedThroughputExceededException"
                        }
}
impl ::std::fmt::Display for ProvisionedThroughputExceededException {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        ::std::write!(f, "ProvisionedThroughputExceededException")?;
        if let ::std::option::Option::Some(inner_3) = &self.message {
             {
                ::std::write!(f, ": {}", inner_3)?;
            }
        }
        Ok(())
    }
}
impl ::std::error::Error for ProvisionedThroughputExceededException {}
impl  ProvisionedThroughputExceededException  {
    /// Creates a new builder-style object to manufacture [`ProvisionedThroughputExceededException`](crate::error::ProvisionedThroughputExceededException).
    pub fn builder() -> crate::error::provisioned_throughput_exceeded_exception::Builder  {
        crate::error::provisioned_throughput_exceeded_exception::Builder::default()
    }
}

#[allow(missing_docs)] // documentation missing in model
#[derive(::std::clone::Clone, ::std::cmp::Eq, ::std::cmp::PartialEq, ::std::fmt::Debug, ::std::hash::Hash)]
pub struct InternalServerError  {
    #[allow(missing_docs)] // documentation missing in model
    pub message: ::std::option::Option<::std::string::String>,
}
impl InternalServerError {
    /// Returns the error message.
                        pub fn message(&self) -> ::std::option::Option<&str> { self.message.as_deref() }
    #[doc(hidden)]
                        /// Returns the error name.
                        pub fn name(&self) -> &'static str {
                            "InternalServerError"
                        }
}
impl ::std::fmt::Display for InternalServerError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        ::std::write!(f, "InternalServerError")?;
        if let ::std::option::Option::Some(inner_4) = &self.message {
             {
                ::std::write!(f, ": {}", inner_4)?;
            }
        }
        Ok(())
    }
}
impl ::std::error::Error for InternalServerError {}
impl  InternalServerError  {
    /// Creates a new builder-style object to manufacture [`InternalServerError`](crate::error::InternalServerError).
    pub fn builder() -> crate::error::internal_server_error::Builder  {
        crate::error::internal_server_error::Builder::default()
    }
}

/// A standard error for input validation failures. This should be thrown by services when a member of the input structure falls outside of the modeled or documented constraints.
#[derive(::std::clone::Clone, ::std::cmp::Eq, ::std::cmp::PartialEq, ::std::fmt::Debug, ::std::hash::Hash)]
pub struct ValidationException  {
    /// A summary of the validation failure.
    pub message: ::std::string::String,
    /// A list of specific failures encountered while validating the input. A member can appear in this list more than once if it failed to satisfy multiple constraints.
    pub field_list: ::std::option::Option<::std::vec::Vec::<crate::model::ValidationExceptionField>>,
}
impl  ValidationException  {
    /// A list of specific failures encountered while validating the input. A member can appear in this list more than once if it failed to satisfy multiple constraints.
    pub fn field_list(&self) -> ::std::option::Option<&[crate::model::ValidationExceptionField]> {
        self.field_list.as_deref()
    }
}
impl ValidationException {
    /// Returns the error message.
                        pub fn message(&self) -> &str { &self.message }
    #[doc(hidden)]
                        /// Returns the error name.
                        pub fn name(&self) -> &'static str {
                            "ValidationException"
                        }
}
impl ::std::fmt::Display for ValidationException {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        ::std::write!(f, "ValidationException")?;
         {
            ::std::write!(f, ": {}", &self.message)?;
        }
        Ok(())
    }
}
impl ::std::error::Error for ValidationException {}
impl  ValidationException  {
    /// Creates a new builder-style object to manufacture [`ValidationException`](crate::error::ValidationException).
    pub fn builder() -> crate::error::validation_exception::Builder  {
        crate::error::validation_exception::Builder::default()
    }
}

/// Error type for the `GetItem` operation.
/// Each variant represents an error that can occur for the `GetItem` operation.
#[derive(::std::fmt::Debug)]
pub enum GetItemError {
    /// A standard error for input validation failures. This should be thrown by services when a member of the input structure falls outside of the modeled or documented constraints.
    ValidationException(crate::error::ValidationException),
    #[allow(missing_docs)] // documentation missing in model
    InternalServerError(crate::error::InternalServerError),
    #[allow(missing_docs)] // documentation missing in model
    ProvisionedThroughputExceededException(crate::error::ProvisionedThroughputExceededException),
    #[allow(missing_docs)] // documentation missing in model
    ResourceNotFoundException(crate::error::ResourceNotFoundException),
}
impl ::std::fmt::Display for GetItemError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match &self {
            GetItemError::ValidationException(_inner) =>
            _inner.fmt(f)
            ,
            GetItemError::InternalServerError(_inner) =>
            _inner.fmt(f)
            ,
            GetItemError::ProvisionedThroughputExceededException(_inner) =>
            _inner.fmt(f)
            ,
            GetItemError::ResourceNotFoundException(_inner) =>
            _inner.fmt(f)
            ,
        }
    }
}
impl GetItemError {
    /// Returns `true` if the error kind is `GetItemError::ValidationException`.
    pub fn is_validation_exception(&self) -> bool {
        matches!(&self, GetItemError::ValidationException(_))
    }
    /// Returns `true` if the error kind is `GetItemError::InternalServerError`.
    pub fn is_internal_server_error(&self) -> bool {
        matches!(&self, GetItemError::InternalServerError(_))
    }
    /// Returns `true` if the error kind is `GetItemError::ProvisionedThroughputExceededException`.
    pub fn is_provisioned_throughput_exceeded_exception(&self) -> bool {
        matches!(&self, GetItemError::ProvisionedThroughputExceededException(_))
    }
    /// Returns `true` if the error kind is `GetItemError::ResourceNotFoundException`.
    pub fn is_resource_not_found_exception(&self) -> bool {
        matches!(&self, GetItemError::ResourceNotFoundException(_))
    }
    /// Returns the error name string by matching the correct variant.
    pub fn name(&self) -> &'static str {
        match &self {
            GetItemError::ValidationException(_inner) =>
            _inner.name()
            ,
            GetItemError::InternalServerError(_inner) =>
            _inner.name()
            ,
            GetItemError::ProvisionedThroughputExceededException(_inner) =>
            _inner.name()
            ,
            GetItemError::ResourceNotFoundException(_inner) =>
            _inner.name()
            ,
        }
    }
}
impl ::std::error::Error for GetItemError {
    fn source(&self) -> std::option::Option<&(dyn ::std::error::Error + 'static)> {
        match &self {
            GetItemError::ValidationException(_inner) =>
            Some(_inner)
            ,
            GetItemError::InternalServerError(_inner) =>
            Some(_inner)
            ,
            GetItemError::ProvisionedThroughputExceededException(_inner) =>
            Some(_inner)
            ,
            GetItemError::ResourceNotFoundException(_inner) =>
            Some(_inner)
            ,
        }
    }
}
impl ::std::convert::From<crate::error::ValidationException> for crate::error::GetItemError {
    fn from(variant: crate::error::ValidationException) -> crate::error::GetItemError {
        Self::ValidationException(variant)
    }
}
impl ::std::convert::From<crate::error::InternalServerError> for crate::error::GetItemError {
    fn from(variant: crate::error::InternalServerError) -> crate::error::GetItemError {
        Self::InternalServerError(variant)
    }
}
impl ::std::convert::From<crate::error::ProvisionedThroughputExceededException> for crate::error::GetItemError {
    fn from(variant: crate::error::ProvisionedThroughputExceededException) -> crate::error::GetItemError {
        Self::ProvisionedThroughputExceededException(variant)
    }
}
impl ::std::convert::From<crate::error::ResourceNotFoundException> for crate::error::GetItemError {
    fn from(variant: crate::error::ResourceNotFoundException) -> crate::error::GetItemError {
        Self::ResourceNotFoundException(variant)
    }
}
/// See [`ConditionalCheckFailedException`](crate::error::ConditionalCheckFailedException).
pub mod conditional_check_failed_exception {
    
    impl ::std::convert::From<Builder > for crate::error::ConditionalCheckFailedException  {
                    fn from(builder: Builder) -> Self {
                        builder.build()
                    }
                }
    /// A builder for [`ConditionalCheckFailedException`](crate::error::ConditionalCheckFailedException).
    #[derive(::std::clone::Clone, ::std::default::Default, ::std::fmt::Debug)]
    pub struct Builder {
        pub(crate) message: ::std::option::Option<::std::string::String>,
        pub(crate) item: ::std::option::Option<::std::collections::HashMap::<::std::string::String, crate::model::AttributeValue>>,
    }
    impl  Builder  {
        #[allow(missing_docs)] // documentation missing in model
        pub fn message(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
            self.message =
                input
            ; self
        }
        #[allow(missing_docs)] // documentation missing in model
        pub fn item(mut self, input: ::std::option::Option<::std::collections::HashMap::<::std::string::String, crate::model::AttributeValue>>) -> Self {
            self.item =
                input
            ; self
        }
        /// Consumes the builder and constructs a [`ConditionalCheckFailedException`](crate::error::ConditionalCheckFailedException).
        pub fn build(self) -> crate::error::ConditionalCheckFailedException {
                        self.build_enforcing_all_constraints()
                    }
        fn build_enforcing_all_constraints(self) -> crate::error::ConditionalCheckFailedException {
            crate::error::ConditionalCheckFailedException {
                message: self.message
                ,
                item: self.item
                ,
            }
        }
    }
    
    
    
    
}
/// See [`ResourceNotFoundException`](crate::error::ResourceNotFoundException).
pub mod resource_not_found_exception {
    
    impl ::std::convert::From<Builder > for crate::error::ResourceNotFoundException  {
                    fn from(builder: Builder) -> Self {
                        builder.build()
                    }
                }
    /// A builder for [`ResourceNotFoundException`](crate::error::ResourceNotFoundException).
    #[derive(::std::clone::Clone, ::std::default::Default, ::std::fmt::Debug)]
    pub struct Builder {
        pub(crate) message: ::std::option::Option<::std::string::String>,
    }
    impl  Builder  {
        #[allow(missing_docs)] // documentation missing in model
        pub fn message(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
            self.message =
                input
            ; self
        }
        /// Consumes the builder and constructs a [`ResourceNotFoundException`](crate::error::ResourceNotFoundException).
        pub fn build(self) -> crate::error::ResourceNotFoundException {
                        self.build_enforcing_all_constraints()
                    }
        fn build_enforcing_all_constraints(self) -> crate::error::ResourceNotFoundException {
            crate::error::ResourceNotFoundException {
                message: self.message
                ,
            }
        }
    }
    
    
    
    
}
/// See [`ProvisionedThroughputExceededException`](crate::error::ProvisionedThroughputExceededException).
pub mod provisioned_throughput_exceeded_exception {
    
    impl ::std::convert::From<Builder > for crate::error::ProvisionedThroughputExceededException  {
                    fn from(builder: Builder) -> Self {
                        builder.build()
                    }
                }
    /// A builder for [`ProvisionedThroughputExceededException`](crate::error::ProvisionedThroughputExceededException).
    #[derive(::std::clone::Clone, ::std::default::Default, ::std::fmt::Debug)]
    pub struct Builder {
        pub(crate) message: ::std::option::Option<::std::string::String>,
    }
    impl  Builder  {
        #[allow(missing_docs)] // documentation missing in model
        pub fn message(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
            self.message =
                input
            ; self
        }
        /// Consumes the builder and constructs a [`ProvisionedThroughputExceededException`](crate::error::ProvisionedThroughputExceededException).
        pub fn build(self) -> crate::error::ProvisionedThroughputExceededException {
                        self.build_enforcing_all_constraints()
                    }
        fn build_enforcing_all_constraints(self) -> crate::error::ProvisionedThroughputExceededException {
            crate::error::ProvisionedThroughputExceededException {
                message: self.message
                ,
            }
        }
    }
    
    
    
    
}
/// See [`InternalServerError`](crate::error::InternalServerError).
pub mod internal_server_error {
    
    impl ::std::convert::From<Builder > for crate::error::InternalServerError  {
                    fn from(builder: Builder) -> Self {
                        builder.build()
                    }
                }
    /// A builder for [`InternalServerError`](crate::error::InternalServerError).
    #[derive(::std::clone::Clone, ::std::default::Default, ::std::fmt::Debug)]
    pub struct Builder {
        pub(crate) message: ::std::option::Option<::std::string::String>,
    }
    impl  Builder  {
        #[allow(missing_docs)] // documentation missing in model
        pub fn message(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
            self.message =
                input
            ; self
        }
        /// Consumes the builder and constructs a [`InternalServerError`](crate::error::InternalServerError).
        pub fn build(self) -> crate::error::InternalServerError {
                        self.build_enforcing_all_constraints()
                    }
        fn build_enforcing_all_constraints(self) -> crate::error::InternalServerError {
            crate::error::InternalServerError {
                message: self.message
                ,
            }
        }
    }
    
    
    
    
}
/// See [`ValidationException`](crate::error::ValidationException).
pub mod validation_exception {
    
    #[derive(::std::cmp::PartialEq, ::std::fmt::Debug)]
    /// Holds one variant for each of the ways the builder can fail.
    #[non_exhaustive]
    #[allow(clippy::enum_variant_names)]
                pub enum ConstraintViolation {
        /// `message` was not provided but it is required when building `ValidationException`.
        MissingMessage,
    }
    impl ::std::fmt::Display for ConstraintViolation {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            match self {
                ConstraintViolation::MissingMessage => write!(f, "`message` was not provided but it is required when building `ValidationException`"),
            }
        }
    }
    impl ::std::error::Error for ConstraintViolation { }
    impl  ::std::convert::TryFrom<Builder > for crate::error::ValidationException {
                    type Error = ConstraintViolation;
    
                    fn try_from(builder: Builder ) -> ::std::result::Result<Self, Self::Error> {
                        builder.build()
                    }
                }
    /// A builder for [`ValidationException`](crate::error::ValidationException).
    #[derive(::std::clone::Clone, ::std::default::Default, ::std::fmt::Debug)]
    pub struct Builder {
        pub(crate) message: ::std::option::Option<::std::string::String>,
        pub(crate) field_list: ::std::option::Option<::std::vec::Vec::<crate::model::ValidationExceptionField>>,
    }
    impl  Builder  {
        /// A summary of the validation failure.
        pub fn message(mut self, input: ::std::string::String) -> Self {
            self.message =
                Some(
                    input
                )
            ; self
        }
        /// A list of specific failures encountered while validating the input. A member can appear in this list more than once if it failed to satisfy multiple constraints.
        pub fn field_list(mut self, input: ::std::option::Option<::std::vec::Vec::<crate::model::ValidationExceptionField>>) -> Self {
            self.field_list =
                input
            ; self
        }
        /// Consumes the builder and constructs a [`ValidationException`](crate::error::ValidationException).
        /// 
        /// The builder fails to construct a [`ValidationException`](crate::error::ValidationException) if a [`ConstraintViolation`] occurs.
        /// 
        pub fn build(self) -> Result<crate::error::ValidationException , ConstraintViolation> {
                        self.build_enforcing_all_constraints()
                    }
        fn build_enforcing_all_constraints(self) -> Result<crate::error::ValidationException , ConstraintViolation> {
            Ok(
                crate::error::ValidationException {
                    message: self.message
                        .ok_or(ConstraintViolation::MissingMessage)?
                    ,
                    field_list: self.field_list
                    ,
                }
            )
        }
    }
    
    
    
    
}

