// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[derive(::std::clone::Clone, ::std::cmp::Eq, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct PutItemOutput  {
    #[allow(missing_docs)] // documentation missing in model
    pub attributes: ::std::option::Option<::std::collections::HashMap::<::std::string::String, crate::model::AttributeValue>>,
}
impl  PutItemOutput  {
    #[allow(missing_docs)] // documentation missing in model
    pub fn attributes(&self) -> ::std::option::Option<&::std::collections::HashMap::<::std::string::String, crate::model::AttributeValue>> {
        self.attributes.as_ref()
    }
}
impl  PutItemOutput  {
    /// Creates a new builder-style object to manufacture [`PutItemOutput`](crate::output::PutItemOutput).
    pub fn builder() -> crate::output::put_item_output::Builder  {
        crate::output::put_item_output::Builder::default()
    }
}

#[allow(missing_docs)] // documentation missing in model
#[derive(::std::clone::Clone, ::std::cmp::Eq, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct GetItemOutput  {
    #[allow(missing_docs)] // documentation missing in model
    pub item: ::std::option::Option<::std::collections::HashMap::<::std::string::String, crate::model::AttributeValue>>,
}
impl  GetItemOutput  {
    #[allow(missing_docs)] // documentation missing in model
    pub fn item(&self) -> ::std::option::Option<&::std::collections::HashMap::<::std::string::String, crate::model::AttributeValue>> {
        self.item.as_ref()
    }
}
impl  GetItemOutput  {
    /// Creates a new builder-style object to manufacture [`GetItemOutput`](crate::output::GetItemOutput).
    pub fn builder() -> crate::output::get_item_output::Builder  {
        crate::output::get_item_output::Builder::default()
    }
}
/// See [`PutItemOutput`](crate::output::PutItemOutput).
pub mod put_item_output {
    
    impl ::std::convert::From<Builder > for crate::output::PutItemOutput  {
                    fn from(builder: Builder) -> Self {
                        builder.build()
                    }
                }
    /// A builder for [`PutItemOutput`](crate::output::PutItemOutput).
    #[derive(::std::clone::Clone, ::std::default::Default, ::std::fmt::Debug)]
    pub struct Builder {
        pub(crate) attributes: ::std::option::Option<::std::collections::HashMap::<::std::string::String, crate::model::AttributeValue>>,
    }
    impl  Builder  {
        #[allow(missing_docs)] // documentation missing in model
        pub fn attributes(mut self, input: ::std::option::Option<::std::collections::HashMap::<::std::string::String, crate::model::AttributeValue>>) -> Self {
            self.attributes =
                input
            ; self
        }
        /// Consumes the builder and constructs a [`PutItemOutput`](crate::output::PutItemOutput).
        pub fn build(self) -> crate::output::PutItemOutput {
                        self.build_enforcing_all_constraints()
                    }
        fn build_enforcing_all_constraints(self) -> crate::output::PutItemOutput {
            crate::output::PutItemOutput {
                attributes: self.attributes
                ,
            }
        }
    }
    
    
    
    
}
/// See [`GetItemOutput`](crate::output::GetItemOutput).
pub mod get_item_output {
    
    impl ::std::convert::From<Builder > for crate::output::GetItemOutput  {
                    fn from(builder: Builder) -> Self {
                        builder.build()
                    }
                }
    /// A builder for [`GetItemOutput`](crate::output::GetItemOutput).
    #[derive(::std::clone::Clone, ::std::default::Default, ::std::fmt::Debug)]
    pub struct Builder {
        pub(crate) item: ::std::option::Option<::std::collections::HashMap::<::std::string::String, crate::model::AttributeValue>>,
    }
    impl  Builder  {
        #[allow(missing_docs)] // documentation missing in model
        pub fn item(mut self, input: ::std::option::Option<::std::collections::HashMap::<::std::string::String, crate::model::AttributeValue>>) -> Self {
            self.item =
                input
            ; self
        }
        /// Consumes the builder and constructs a [`GetItemOutput`](crate::output::GetItemOutput).
        pub fn build(self) -> crate::output::GetItemOutput {
                        self.build_enforcing_all_constraints()
                    }
        fn build_enforcing_all_constraints(self) -> crate::output::GetItemOutput {
            crate::output::GetItemOutput {
                item: self.item
                ,
            }
        }
    }
    
    
    
    
}

