// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[derive(::std::clone::Clone, ::std::cmp::Eq, ::std::cmp::PartialEq, ::std::fmt::Debug, ::std::hash::Hash)]
pub struct CreateTableOutput  {
    #[allow(missing_docs)] // documentation missing in model
    pub table_description: ::std::option::Option<crate::model::TableDescription>,
}
impl  CreateTableOutput  {
    #[allow(missing_docs)] // documentation missing in model
    pub fn table_description(&self) -> ::std::option::Option<&crate::model::TableDescription> {
        self.table_description.as_ref()
    }
}
impl  CreateTableOutput  {
    /// Creates a new builder-style object to manufacture [`CreateTableOutput`](crate::output::CreateTableOutput).
    pub fn builder() -> crate::output::create_table_output::Builder  {
        crate::output::create_table_output::Builder::default()
    }
}

#[allow(missing_docs)] // documentation missing in model
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct PutItemOutput  {
    #[allow(missing_docs)] // documentation missing in model
    pub attributes: ::std::option::Option<::std::collections::HashMap::<::std::string::String, crate::model::AttributeValue>>,
    #[allow(missing_docs)] // documentation missing in model
    pub consumed_capacity: ::std::option::Option<crate::model::ConsumedCapacity>,
    #[allow(missing_docs)] // documentation missing in model
    pub item_collection_metrics: ::std::option::Option<crate::model::ItemCollectionMetrics>,
}
impl  PutItemOutput  {
    #[allow(missing_docs)] // documentation missing in model
    pub fn attributes(&self) -> ::std::option::Option<&::std::collections::HashMap::<::std::string::String, crate::model::AttributeValue>> {
        self.attributes.as_ref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn consumed_capacity(&self) -> ::std::option::Option<&crate::model::ConsumedCapacity> {
        self.consumed_capacity.as_ref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn item_collection_metrics(&self) -> ::std::option::Option<&crate::model::ItemCollectionMetrics> {
        self.item_collection_metrics.as_ref()
    }
}
impl  PutItemOutput  {
    /// Creates a new builder-style object to manufacture [`PutItemOutput`](crate::output::PutItemOutput).
    pub fn builder() -> crate::output::put_item_output::Builder  {
        crate::output::put_item_output::Builder::default()
    }
}

#[allow(missing_docs)] // documentation missing in model
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct GetItemOutput  {
    #[allow(missing_docs)] // documentation missing in model
    pub item: ::std::option::Option<::std::collections::HashMap::<::std::string::String, crate::model::AttributeValue>>,
    #[allow(missing_docs)] // documentation missing in model
    pub consumed_capacity: ::std::option::Option<crate::model::ConsumedCapacity>,
}
impl  GetItemOutput  {
    #[allow(missing_docs)] // documentation missing in model
    pub fn item(&self) -> ::std::option::Option<&::std::collections::HashMap::<::std::string::String, crate::model::AttributeValue>> {
        self.item.as_ref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn consumed_capacity(&self) -> ::std::option::Option<&crate::model::ConsumedCapacity> {
        self.consumed_capacity.as_ref()
    }
}
impl  GetItemOutput  {
    /// Creates a new builder-style object to manufacture [`GetItemOutput`](crate::output::GetItemOutput).
    pub fn builder() -> crate::output::get_item_output::Builder  {
        crate::output::get_item_output::Builder::default()
    }
}
/// See [`CreateTableOutput`](crate::output::CreateTableOutput).
pub mod create_table_output {
    
    impl ::std::convert::From<Builder > for crate::output::CreateTableOutput  {
                    fn from(builder: Builder) -> Self {
                        builder.build()
                    }
                }
    /// A builder for [`CreateTableOutput`](crate::output::CreateTableOutput).
    #[derive(::std::clone::Clone, ::std::default::Default, ::std::fmt::Debug)]
    pub struct Builder {
        pub(crate) table_description: ::std::option::Option<crate::model::TableDescription>,
    }
    impl  Builder  {
        #[allow(missing_docs)] // documentation missing in model
        pub fn table_description(mut self, input: ::std::option::Option<crate::model::TableDescription>) -> Self {
            self.table_description =
                input
            ; self
        }
        /// Consumes the builder and constructs a [`CreateTableOutput`](crate::output::CreateTableOutput).
        pub fn build(self) -> crate::output::CreateTableOutput {
                        self.build_enforcing_all_constraints()
                    }
        fn build_enforcing_all_constraints(self) -> crate::output::CreateTableOutput {
            crate::output::CreateTableOutput {
                table_description: self.table_description
                ,
            }
        }
    }
    
    
    
    
}
/// See [`PutItemOutput`](crate::output::PutItemOutput).
pub mod put_item_output {
    
    impl ::std::convert::From<Builder > for crate::output::PutItemOutput  {
                    fn from(builder: Builder) -> Self {
                        builder.build()
                    }
                }
    /// A builder for [`PutItemOutput`](crate::output::PutItemOutput).
    #[derive(::std::clone::Clone, ::std::default::Default, ::std::fmt::Debug)]
    pub struct Builder {
        pub(crate) attributes: ::std::option::Option<::std::collections::HashMap::<::std::string::String, crate::model::AttributeValue>>,
        pub(crate) consumed_capacity: ::std::option::Option<crate::model::ConsumedCapacity>,
        pub(crate) item_collection_metrics: ::std::option::Option<crate::model::ItemCollectionMetrics>,
    }
    impl  Builder  {
        #[allow(missing_docs)] // documentation missing in model
        pub fn attributes(mut self, input: ::std::option::Option<::std::collections::HashMap::<::std::string::String, crate::model::AttributeValue>>) -> Self {
            self.attributes =
                input
            ; self
        }
        #[allow(missing_docs)] // documentation missing in model
        pub fn consumed_capacity(mut self, input: ::std::option::Option<crate::model::ConsumedCapacity>) -> Self {
            self.consumed_capacity =
                input
            ; self
        }
        #[allow(missing_docs)] // documentation missing in model
        pub fn item_collection_metrics(mut self, input: ::std::option::Option<crate::model::ItemCollectionMetrics>) -> Self {
            self.item_collection_metrics =
                input
            ; self
        }
        /// Consumes the builder and constructs a [`PutItemOutput`](crate::output::PutItemOutput).
        pub fn build(self) -> crate::output::PutItemOutput {
                        self.build_enforcing_all_constraints()
                    }
        fn build_enforcing_all_constraints(self) -> crate::output::PutItemOutput {
            crate::output::PutItemOutput {
                attributes: self.attributes
                ,
                consumed_capacity: self.consumed_capacity
                ,
                item_collection_metrics: self.item_collection_metrics
                ,
            }
        }
    }
    
    
    
    
}
/// See [`GetItemOutput`](crate::output::GetItemOutput).
pub mod get_item_output {
    
    impl ::std::convert::From<Builder > for crate::output::GetItemOutput  {
                    fn from(builder: Builder) -> Self {
                        builder.build()
                    }
                }
    /// A builder for [`GetItemOutput`](crate::output::GetItemOutput).
    #[derive(::std::clone::Clone, ::std::default::Default, ::std::fmt::Debug)]
    pub struct Builder {
        pub(crate) item: ::std::option::Option<::std::collections::HashMap::<::std::string::String, crate::model::AttributeValue>>,
        pub(crate) consumed_capacity: ::std::option::Option<crate::model::ConsumedCapacity>,
    }
    impl  Builder  {
        #[allow(missing_docs)] // documentation missing in model
        pub fn item(mut self, input: ::std::option::Option<::std::collections::HashMap::<::std::string::String, crate::model::AttributeValue>>) -> Self {
            self.item =
                input
            ; self
        }
        #[allow(missing_docs)] // documentation missing in model
        pub fn consumed_capacity(mut self, input: ::std::option::Option<crate::model::ConsumedCapacity>) -> Self {
            self.consumed_capacity =
                input
            ; self
        }
        /// Consumes the builder and constructs a [`GetItemOutput`](crate::output::GetItemOutput).
        pub fn build(self) -> crate::output::GetItemOutput {
                        self.build_enforcing_all_constraints()
                    }
        fn build_enforcing_all_constraints(self) -> crate::output::GetItemOutput {
            crate::output::GetItemOutput {
                item: self.item
                ,
                consumed_capacity: self.consumed_capacity
                ,
            }
        }
    }
    
    
    
    
}

