// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub(crate) mod shape_get_item;

pub(crate) mod shape_put_item;

pub(crate) mod shape_conditional_check_failed_exception;

pub(crate) fn or_empty_doc(data: &[u8]) -> &[u8] {
                    if data.is_empty() {
                        b"{}"
                    } else {
                        data
                    }
                }

pub(crate) mod shape_get_item_output;

pub(crate) mod shape_internal_server_error;

pub(crate) mod shape_provisioned_throughput_exceeded_exception;

pub(crate) mod shape_put_item_output;

pub(crate) mod shape_resource_not_found_exception;

pub(crate) mod shape_validation_exception;

pub(crate) mod shape_attribute_map;

pub(crate) mod shape_expression_attribute_name_map;

pub(crate) mod shape_expression_attribute_value_map;

pub(crate) mod shape_key;

pub(crate) mod shape_attribute_value;

pub(crate) mod shape_validation_exception_field;

pub(crate) mod shape_attribute_list;

pub(crate) mod shape_binary_set;

pub(crate) mod shape_number_set;

pub(crate) mod shape_string_set;

