// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub(crate) mod shape_create_table;

pub(crate) mod shape_get_item;

pub(crate) mod shape_put_item;

pub(crate) mod shape_conditional_check_failed_exception;

pub(crate) fn or_empty_doc(data: &[u8]) -> &[u8] {
                    if data.is_empty() {
                        b"{}"
                    } else {
                        data
                    }
                }

pub(crate) mod shape_create_table_output;

pub(crate) mod shape_get_item_output;

pub(crate) mod shape_internal_server_error;

pub(crate) mod shape_invalid_endpoint_exception;

pub(crate) mod shape_item_collection_size_limit_exceeded_exception;

pub(crate) mod shape_limit_exceeded_exception;

pub(crate) mod shape_provisioned_throughput_exceeded_exception;

pub(crate) mod shape_put_item_output;

pub(crate) mod shape_request_limit_exceeded;

pub(crate) mod shape_resource_in_use_exception;

pub(crate) mod shape_resource_not_found_exception;

pub(crate) mod shape_transaction_conflict_exception;

pub(crate) mod shape_validation_exception;

pub(crate) mod shape_attribute_definitions;

pub(crate) mod shape_attribute_name_list;

pub(crate) mod shape_expected_attribute_map;

pub(crate) mod shape_expression_attribute_name_map;

pub(crate) mod shape_expression_attribute_value_map;

pub(crate) mod shape_global_secondary_index_list;

pub(crate) mod shape_key;

pub(crate) mod shape_key_schema;

pub(crate) mod shape_local_secondary_index_list;

pub(crate) mod shape_provisioned_throughput;

pub(crate) mod shape_put_item_input_attribute_map;

pub(crate) mod shape_sse_specification;

pub(crate) mod shape_stream_specification;

pub(crate) mod shape_tag_list;

pub(crate) mod shape_attribute_definition;

pub(crate) mod shape_attribute_value;

pub(crate) mod shape_consumed_capacity;

pub(crate) mod shape_expected_attribute_value;

pub(crate) mod shape_global_secondary_index;

pub(crate) mod shape_item_collection_metrics;

pub(crate) mod shape_key_schema_element;

pub(crate) mod shape_local_secondary_index;

pub(crate) mod shape_table_description;

pub(crate) mod shape_tag;

pub(crate) mod shape_validation_exception_field;

pub(crate) mod shape_archival_summary;

pub(crate) mod shape_attribute_value_list;

pub(crate) mod shape_billing_mode_summary;

pub(crate) mod shape_binary_set_attribute_value;

pub(crate) mod shape_capacity;

pub(crate) mod shape_global_secondary_index_description;

pub(crate) mod shape_list_attribute_value;

pub(crate) mod shape_local_secondary_index_description;

pub(crate) mod shape_map_attribute_value;

pub(crate) mod shape_number_set_attribute_value;

pub(crate) mod shape_projection;

pub(crate) mod shape_provisioned_throughput_description;

pub(crate) mod shape_replica_description;

pub(crate) mod shape_restore_summary;

pub(crate) mod shape_sse_description;

pub(crate) mod shape_string_set_attribute_value;

pub(crate) mod shape_non_key_attribute_name_list;

pub(crate) mod shape_provisioned_throughput_override;

pub(crate) mod shape_replica_global_secondary_index_description;

