// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
/// The service builder for [`DynamoDb20120810`].
                ///
                /// Constructed via [`DynamoDb20120810::builder`].
                pub struct DynamoDb20120810Builder<Body, L, HttpPl, ModelPl> {
                    create_table: Option<::aws_smithy_legacy_http_server::routing::Route<Body>>, get_item: Option<::aws_smithy_legacy_http_server::routing::Route<Body>>, put_item: Option<::aws_smithy_legacy_http_server::routing::Route<Body>>, update_item: Option<::aws_smithy_legacy_http_server::routing::Route<Body>>,
                    layer: L,
                    http_plugin: HttpPl,
                    model_plugin: ModelPl
                }

                impl<Body, L, HttpPl, ModelPl> DynamoDb20120810Builder<Body, L, HttpPl, ModelPl> {
                    /// Sets the [`CreateTable`](crate::operation_shape::CreateTable) operation.
                    ///
                    /// This should be an async function satisfying the [`Handler`](::aws_smithy_legacy_http_server::operation::Handler) trait.
                    /// See the [operation module documentation](::aws_smithy_legacy_http_server::operation) for more information.
                    ///
                    /// # Example
                    ///
                    /// ```no_run
                    /// use dynamodb_local_server_sdk::{DynamoDb20120810, DynamoDb20120810Config};
                    ///
                    /// use dynamodb_local_server_sdk::{input, output, error};
                    ///
                    /// async fn handler(input: input::CreateTableInput) -> Result<output::CreateTableOutput, error::CreateTableError> {
///     todo!()
/// }
                    ///
                    /// let config = DynamoDb20120810Config::builder().build();
                    /// let app = DynamoDb20120810::builder(config)
                    ///     .create_table(handler)
                    ///     /* Set other handlers */
                    ///     .build()
                    ///     .unwrap();
                    /// # let app: DynamoDb20120810<::aws_smithy_legacy_http_server::routing::RoutingService<::aws_smithy_legacy_http_server::protocol::aws_json::router::AwsJsonRouter<::aws_smithy_legacy_http_server::routing::Route>, ::aws_smithy_legacy_http_server::protocol::aws_json_10::AwsJson1_0>> = app;
                    /// ```
                    ///
                    pub fn create_table<HandlerType, HandlerExtractors, UpgradeExtractors>(self, handler: HandlerType) -> Self
                    where
                        HandlerType: ::aws_smithy_legacy_http_server::operation::Handler<crate::operation_shape::CreateTable, HandlerExtractors>,

                        ModelPl: ::aws_smithy_legacy_http_server::plugin::Plugin<
                            DynamoDb20120810<L>,
                            crate::operation_shape::CreateTable,
                            ::aws_smithy_legacy_http_server::operation::IntoService<crate::operation_shape::CreateTable, HandlerType>
                        >,
                        ::aws_smithy_legacy_http_server::operation::UpgradePlugin::<UpgradeExtractors>: ::aws_smithy_legacy_http_server::plugin::Plugin<
                            DynamoDb20120810<L>,
                            crate::operation_shape::CreateTable,
                            ModelPl::Output
                        >,
                        HttpPl: ::aws_smithy_legacy_http_server::plugin::Plugin<
                            DynamoDb20120810<L>,
                            crate::operation_shape::CreateTable,
                            <
                                ::aws_smithy_legacy_http_server::operation::UpgradePlugin::<UpgradeExtractors>
                                as ::aws_smithy_legacy_http_server::plugin::Plugin<
                                    DynamoDb20120810<L>,
                                    crate::operation_shape::CreateTable,
                                    ModelPl::Output
                                >
                            >::Output
                        >,

                        HttpPl::Output: ::tower::Service<::http::Request<Body>, Response = ::http::Response<::aws_smithy_legacy_http_server::body::BoxBody>, Error = ::std::convert::Infallible> + Clone + Send + 'static,
                        <HttpPl::Output as ::tower::Service<::http::Request<Body>>>::Future: Send + 'static,

                    {
                        use ::aws_smithy_legacy_http_server::operation::OperationShapeExt;
                        use ::aws_smithy_legacy_http_server::plugin::Plugin;
                        let svc = crate::operation_shape::CreateTable::from_handler(handler);
                        let svc = self.model_plugin.apply(svc);
                        let svc = ::aws_smithy_legacy_http_server::operation::UpgradePlugin::<UpgradeExtractors>::new().apply(svc);
                        let svc = self.http_plugin.apply(svc);
                        self.create_table_custom(svc)
                    }

                    /// Sets the [`CreateTable`](crate::operation_shape::CreateTable) operation.
                    ///
                    /// This should be an async function satisfying the [`Handler`](::aws_smithy_legacy_http_server::operation::Handler) trait.
                    /// See the [operation module documentation](::aws_smithy_legacy_http_server::operation) for more information.
                    ///
                    /// # Example
                    ///
                    /// ```no_run
                    /// use dynamodb_local_server_sdk::{DynamoDb20120810, DynamoDb20120810Config};
                    ///
                    /// use dynamodb_local_server_sdk::{input, output, error};
                    ///
                    /// async fn handler(input: input::CreateTableInput) -> Result<output::CreateTableOutput, error::CreateTableError> {
///     todo!()
/// }
                    ///
                    /// let config = DynamoDb20120810Config::builder().build();
                    /// let svc = ::tower::util::service_fn(handler);
                    /// let app = DynamoDb20120810::builder(config)
                    ///     .create_table_service(svc)
                    ///     /* Set other handlers */
                    ///     .build()
                    ///     .unwrap();
                    /// # let app: DynamoDb20120810<::aws_smithy_legacy_http_server::routing::RoutingService<::aws_smithy_legacy_http_server::protocol::aws_json::router::AwsJsonRouter<::aws_smithy_legacy_http_server::routing::Route>, ::aws_smithy_legacy_http_server::protocol::aws_json_10::AwsJson1_0>> = app;
                    /// ```
                    ///
                    pub fn create_table_service<S, ServiceExtractors, UpgradeExtractors>(self, service: S) -> Self
                    where
                        S: ::aws_smithy_legacy_http_server::operation::OperationService<crate::operation_shape::CreateTable, ServiceExtractors>,

                        ModelPl: ::aws_smithy_legacy_http_server::plugin::Plugin<
                            DynamoDb20120810<L>,
                            crate::operation_shape::CreateTable,
                            ::aws_smithy_legacy_http_server::operation::Normalize<crate::operation_shape::CreateTable, S>
                        >,
                        ::aws_smithy_legacy_http_server::operation::UpgradePlugin::<UpgradeExtractors>: ::aws_smithy_legacy_http_server::plugin::Plugin<
                            DynamoDb20120810<L>,
                            crate::operation_shape::CreateTable,
                            ModelPl::Output
                        >,
                        HttpPl: ::aws_smithy_legacy_http_server::plugin::Plugin<
                            DynamoDb20120810<L>,
                            crate::operation_shape::CreateTable,
                            <
                                ::aws_smithy_legacy_http_server::operation::UpgradePlugin::<UpgradeExtractors>
                                as ::aws_smithy_legacy_http_server::plugin::Plugin<
                                    DynamoDb20120810<L>,
                                    crate::operation_shape::CreateTable,
                                    ModelPl::Output
                                >
                            >::Output
                        >,

                        HttpPl::Output: ::tower::Service<::http::Request<Body>, Response = ::http::Response<::aws_smithy_legacy_http_server::body::BoxBody>, Error = ::std::convert::Infallible> + Clone + Send + 'static,
                        <HttpPl::Output as ::tower::Service<::http::Request<Body>>>::Future: Send + 'static,

                    {
                        use ::aws_smithy_legacy_http_server::operation::OperationShapeExt;
                        use ::aws_smithy_legacy_http_server::plugin::Plugin;
                        let svc = crate::operation_shape::CreateTable::from_service(service);
                        let svc = self.model_plugin.apply(svc);
                        let svc = ::aws_smithy_legacy_http_server::operation::UpgradePlugin::<UpgradeExtractors>::new().apply(svc);
                        let svc = self.http_plugin.apply(svc);
                        self.create_table_custom(svc)
                    }

                    /// Sets the [`CreateTable`](crate::operation_shape::CreateTable) to a custom [`Service`](tower::Service).
                    /// not constrained by the Smithy contract.
                    fn create_table_custom<S>(mut self, svc: S) -> Self
                    where
                        S: ::tower::Service<::http::Request<Body>, Response = ::http::Response<::aws_smithy_legacy_http_server::body::BoxBody>, Error = ::std::convert::Infallible> + Clone + Send + 'static,
                        S::Future: Send + 'static,
                    {
                        self.create_table = Some(::aws_smithy_legacy_http_server::routing::Route::new(svc));
                        self
                    }

/// Sets the [`GetItem`](crate::operation_shape::GetItem) operation.
                    ///
                    /// This should be an async function satisfying the [`Handler`](::aws_smithy_legacy_http_server::operation::Handler) trait.
                    /// See the [operation module documentation](::aws_smithy_legacy_http_server::operation) for more information.
                    ///
                    /// # Example
                    ///
                    /// ```no_run
                    /// use dynamodb_local_server_sdk::{DynamoDb20120810, DynamoDb20120810Config};
                    ///
                    /// use dynamodb_local_server_sdk::{input, output, error};
                    ///
                    /// async fn handler(input: input::GetItemInput) -> Result<output::GetItemOutput, error::GetItemError> {
///     todo!()
/// }
                    ///
                    /// let config = DynamoDb20120810Config::builder().build();
                    /// let app = DynamoDb20120810::builder(config)
                    ///     .get_item(handler)
                    ///     /* Set other handlers */
                    ///     .build()
                    ///     .unwrap();
                    /// # let app: DynamoDb20120810<::aws_smithy_legacy_http_server::routing::RoutingService<::aws_smithy_legacy_http_server::protocol::aws_json::router::AwsJsonRouter<::aws_smithy_legacy_http_server::routing::Route>, ::aws_smithy_legacy_http_server::protocol::aws_json_10::AwsJson1_0>> = app;
                    /// ```
                    ///
                    pub fn get_item<HandlerType, HandlerExtractors, UpgradeExtractors>(self, handler: HandlerType) -> Self
                    where
                        HandlerType: ::aws_smithy_legacy_http_server::operation::Handler<crate::operation_shape::GetItem, HandlerExtractors>,

                        ModelPl: ::aws_smithy_legacy_http_server::plugin::Plugin<
                            DynamoDb20120810<L>,
                            crate::operation_shape::GetItem,
                            ::aws_smithy_legacy_http_server::operation::IntoService<crate::operation_shape::GetItem, HandlerType>
                        >,
                        ::aws_smithy_legacy_http_server::operation::UpgradePlugin::<UpgradeExtractors>: ::aws_smithy_legacy_http_server::plugin::Plugin<
                            DynamoDb20120810<L>,
                            crate::operation_shape::GetItem,
                            ModelPl::Output
                        >,
                        HttpPl: ::aws_smithy_legacy_http_server::plugin::Plugin<
                            DynamoDb20120810<L>,
                            crate::operation_shape::GetItem,
                            <
                                ::aws_smithy_legacy_http_server::operation::UpgradePlugin::<UpgradeExtractors>
                                as ::aws_smithy_legacy_http_server::plugin::Plugin<
                                    DynamoDb20120810<L>,
                                    crate::operation_shape::GetItem,
                                    ModelPl::Output
                                >
                            >::Output
                        >,

                        HttpPl::Output: ::tower::Service<::http::Request<Body>, Response = ::http::Response<::aws_smithy_legacy_http_server::body::BoxBody>, Error = ::std::convert::Infallible> + Clone + Send + 'static,
                        <HttpPl::Output as ::tower::Service<::http::Request<Body>>>::Future: Send + 'static,

                    {
                        use ::aws_smithy_legacy_http_server::operation::OperationShapeExt;
                        use ::aws_smithy_legacy_http_server::plugin::Plugin;
                        let svc = crate::operation_shape::GetItem::from_handler(handler);
                        let svc = self.model_plugin.apply(svc);
                        let svc = ::aws_smithy_legacy_http_server::operation::UpgradePlugin::<UpgradeExtractors>::new().apply(svc);
                        let svc = self.http_plugin.apply(svc);
                        self.get_item_custom(svc)
                    }

                    /// Sets the [`GetItem`](crate::operation_shape::GetItem) operation.
                    ///
                    /// This should be an async function satisfying the [`Handler`](::aws_smithy_legacy_http_server::operation::Handler) trait.
                    /// See the [operation module documentation](::aws_smithy_legacy_http_server::operation) for more information.
                    ///
                    /// # Example
                    ///
                    /// ```no_run
                    /// use dynamodb_local_server_sdk::{DynamoDb20120810, DynamoDb20120810Config};
                    ///
                    /// use dynamodb_local_server_sdk::{input, output, error};
                    ///
                    /// async fn handler(input: input::GetItemInput) -> Result<output::GetItemOutput, error::GetItemError> {
///     todo!()
/// }
                    ///
                    /// let config = DynamoDb20120810Config::builder().build();
                    /// let svc = ::tower::util::service_fn(handler);
                    /// let app = DynamoDb20120810::builder(config)
                    ///     .get_item_service(svc)
                    ///     /* Set other handlers */
                    ///     .build()
                    ///     .unwrap();
                    /// # let app: DynamoDb20120810<::aws_smithy_legacy_http_server::routing::RoutingService<::aws_smithy_legacy_http_server::protocol::aws_json::router::AwsJsonRouter<::aws_smithy_legacy_http_server::routing::Route>, ::aws_smithy_legacy_http_server::protocol::aws_json_10::AwsJson1_0>> = app;
                    /// ```
                    ///
                    pub fn get_item_service<S, ServiceExtractors, UpgradeExtractors>(self, service: S) -> Self
                    where
                        S: ::aws_smithy_legacy_http_server::operation::OperationService<crate::operation_shape::GetItem, ServiceExtractors>,

                        ModelPl: ::aws_smithy_legacy_http_server::plugin::Plugin<
                            DynamoDb20120810<L>,
                            crate::operation_shape::GetItem,
                            ::aws_smithy_legacy_http_server::operation::Normalize<crate::operation_shape::GetItem, S>
                        >,
                        ::aws_smithy_legacy_http_server::operation::UpgradePlugin::<UpgradeExtractors>: ::aws_smithy_legacy_http_server::plugin::Plugin<
                            DynamoDb20120810<L>,
                            crate::operation_shape::GetItem,
                            ModelPl::Output
                        >,
                        HttpPl: ::aws_smithy_legacy_http_server::plugin::Plugin<
                            DynamoDb20120810<L>,
                            crate::operation_shape::GetItem,
                            <
                                ::aws_smithy_legacy_http_server::operation::UpgradePlugin::<UpgradeExtractors>
                                as ::aws_smithy_legacy_http_server::plugin::Plugin<
                                    DynamoDb20120810<L>,
                                    crate::operation_shape::GetItem,
                                    ModelPl::Output
                                >
                            >::Output
                        >,

                        HttpPl::Output: ::tower::Service<::http::Request<Body>, Response = ::http::Response<::aws_smithy_legacy_http_server::body::BoxBody>, Error = ::std::convert::Infallible> + Clone + Send + 'static,
                        <HttpPl::Output as ::tower::Service<::http::Request<Body>>>::Future: Send + 'static,

                    {
                        use ::aws_smithy_legacy_http_server::operation::OperationShapeExt;
                        use ::aws_smithy_legacy_http_server::plugin::Plugin;
                        let svc = crate::operation_shape::GetItem::from_service(service);
                        let svc = self.model_plugin.apply(svc);
                        let svc = ::aws_smithy_legacy_http_server::operation::UpgradePlugin::<UpgradeExtractors>::new().apply(svc);
                        let svc = self.http_plugin.apply(svc);
                        self.get_item_custom(svc)
                    }

                    /// Sets the [`GetItem`](crate::operation_shape::GetItem) to a custom [`Service`](tower::Service).
                    /// not constrained by the Smithy contract.
                    fn get_item_custom<S>(mut self, svc: S) -> Self
                    where
                        S: ::tower::Service<::http::Request<Body>, Response = ::http::Response<::aws_smithy_legacy_http_server::body::BoxBody>, Error = ::std::convert::Infallible> + Clone + Send + 'static,
                        S::Future: Send + 'static,
                    {
                        self.get_item = Some(::aws_smithy_legacy_http_server::routing::Route::new(svc));
                        self
                    }

/// Sets the [`PutItem`](crate::operation_shape::PutItem) operation.
                    ///
                    /// This should be an async function satisfying the [`Handler`](::aws_smithy_legacy_http_server::operation::Handler) trait.
                    /// See the [operation module documentation](::aws_smithy_legacy_http_server::operation) for more information.
                    ///
                    /// # Example
                    ///
                    /// ```no_run
                    /// use dynamodb_local_server_sdk::{DynamoDb20120810, DynamoDb20120810Config};
                    ///
                    /// use dynamodb_local_server_sdk::{input, output, error};
                    ///
                    /// async fn handler(input: input::PutItemInput) -> Result<output::PutItemOutput, error::PutItemError> {
///     todo!()
/// }
                    ///
                    /// let config = DynamoDb20120810Config::builder().build();
                    /// let app = DynamoDb20120810::builder(config)
                    ///     .put_item(handler)
                    ///     /* Set other handlers */
                    ///     .build()
                    ///     .unwrap();
                    /// # let app: DynamoDb20120810<::aws_smithy_legacy_http_server::routing::RoutingService<::aws_smithy_legacy_http_server::protocol::aws_json::router::AwsJsonRouter<::aws_smithy_legacy_http_server::routing::Route>, ::aws_smithy_legacy_http_server::protocol::aws_json_10::AwsJson1_0>> = app;
                    /// ```
                    ///
                    pub fn put_item<HandlerType, HandlerExtractors, UpgradeExtractors>(self, handler: HandlerType) -> Self
                    where
                        HandlerType: ::aws_smithy_legacy_http_server::operation::Handler<crate::operation_shape::PutItem, HandlerExtractors>,

                        ModelPl: ::aws_smithy_legacy_http_server::plugin::Plugin<
                            DynamoDb20120810<L>,
                            crate::operation_shape::PutItem,
                            ::aws_smithy_legacy_http_server::operation::IntoService<crate::operation_shape::PutItem, HandlerType>
                        >,
                        ::aws_smithy_legacy_http_server::operation::UpgradePlugin::<UpgradeExtractors>: ::aws_smithy_legacy_http_server::plugin::Plugin<
                            DynamoDb20120810<L>,
                            crate::operation_shape::PutItem,
                            ModelPl::Output
                        >,
                        HttpPl: ::aws_smithy_legacy_http_server::plugin::Plugin<
                            DynamoDb20120810<L>,
                            crate::operation_shape::PutItem,
                            <
                                ::aws_smithy_legacy_http_server::operation::UpgradePlugin::<UpgradeExtractors>
                                as ::aws_smithy_legacy_http_server::plugin::Plugin<
                                    DynamoDb20120810<L>,
                                    crate::operation_shape::PutItem,
                                    ModelPl::Output
                                >
                            >::Output
                        >,

                        HttpPl::Output: ::tower::Service<::http::Request<Body>, Response = ::http::Response<::aws_smithy_legacy_http_server::body::BoxBody>, Error = ::std::convert::Infallible> + Clone + Send + 'static,
                        <HttpPl::Output as ::tower::Service<::http::Request<Body>>>::Future: Send + 'static,

                    {
                        use ::aws_smithy_legacy_http_server::operation::OperationShapeExt;
                        use ::aws_smithy_legacy_http_server::plugin::Plugin;
                        let svc = crate::operation_shape::PutItem::from_handler(handler);
                        let svc = self.model_plugin.apply(svc);
                        let svc = ::aws_smithy_legacy_http_server::operation::UpgradePlugin::<UpgradeExtractors>::new().apply(svc);
                        let svc = self.http_plugin.apply(svc);
                        self.put_item_custom(svc)
                    }

                    /// Sets the [`PutItem`](crate::operation_shape::PutItem) operation.
                    ///
                    /// This should be an async function satisfying the [`Handler`](::aws_smithy_legacy_http_server::operation::Handler) trait.
                    /// See the [operation module documentation](::aws_smithy_legacy_http_server::operation) for more information.
                    ///
                    /// # Example
                    ///
                    /// ```no_run
                    /// use dynamodb_local_server_sdk::{DynamoDb20120810, DynamoDb20120810Config};
                    ///
                    /// use dynamodb_local_server_sdk::{input, output, error};
                    ///
                    /// async fn handler(input: input::PutItemInput) -> Result<output::PutItemOutput, error::PutItemError> {
///     todo!()
/// }
                    ///
                    /// let config = DynamoDb20120810Config::builder().build();
                    /// let svc = ::tower::util::service_fn(handler);
                    /// let app = DynamoDb20120810::builder(config)
                    ///     .put_item_service(svc)
                    ///     /* Set other handlers */
                    ///     .build()
                    ///     .unwrap();
                    /// # let app: DynamoDb20120810<::aws_smithy_legacy_http_server::routing::RoutingService<::aws_smithy_legacy_http_server::protocol::aws_json::router::AwsJsonRouter<::aws_smithy_legacy_http_server::routing::Route>, ::aws_smithy_legacy_http_server::protocol::aws_json_10::AwsJson1_0>> = app;
                    /// ```
                    ///
                    pub fn put_item_service<S, ServiceExtractors, UpgradeExtractors>(self, service: S) -> Self
                    where
                        S: ::aws_smithy_legacy_http_server::operation::OperationService<crate::operation_shape::PutItem, ServiceExtractors>,

                        ModelPl: ::aws_smithy_legacy_http_server::plugin::Plugin<
                            DynamoDb20120810<L>,
                            crate::operation_shape::PutItem,
                            ::aws_smithy_legacy_http_server::operation::Normalize<crate::operation_shape::PutItem, S>
                        >,
                        ::aws_smithy_legacy_http_server::operation::UpgradePlugin::<UpgradeExtractors>: ::aws_smithy_legacy_http_server::plugin::Plugin<
                            DynamoDb20120810<L>,
                            crate::operation_shape::PutItem,
                            ModelPl::Output
                        >,
                        HttpPl: ::aws_smithy_legacy_http_server::plugin::Plugin<
                            DynamoDb20120810<L>,
                            crate::operation_shape::PutItem,
                            <
                                ::aws_smithy_legacy_http_server::operation::UpgradePlugin::<UpgradeExtractors>
                                as ::aws_smithy_legacy_http_server::plugin::Plugin<
                                    DynamoDb20120810<L>,
                                    crate::operation_shape::PutItem,
                                    ModelPl::Output
                                >
                            >::Output
                        >,

                        HttpPl::Output: ::tower::Service<::http::Request<Body>, Response = ::http::Response<::aws_smithy_legacy_http_server::body::BoxBody>, Error = ::std::convert::Infallible> + Clone + Send + 'static,
                        <HttpPl::Output as ::tower::Service<::http::Request<Body>>>::Future: Send + 'static,

                    {
                        use ::aws_smithy_legacy_http_server::operation::OperationShapeExt;
                        use ::aws_smithy_legacy_http_server::plugin::Plugin;
                        let svc = crate::operation_shape::PutItem::from_service(service);
                        let svc = self.model_plugin.apply(svc);
                        let svc = ::aws_smithy_legacy_http_server::operation::UpgradePlugin::<UpgradeExtractors>::new().apply(svc);
                        let svc = self.http_plugin.apply(svc);
                        self.put_item_custom(svc)
                    }

                    /// Sets the [`PutItem`](crate::operation_shape::PutItem) to a custom [`Service`](tower::Service).
                    /// not constrained by the Smithy contract.
                    fn put_item_custom<S>(mut self, svc: S) -> Self
                    where
                        S: ::tower::Service<::http::Request<Body>, Response = ::http::Response<::aws_smithy_legacy_http_server::body::BoxBody>, Error = ::std::convert::Infallible> + Clone + Send + 'static,
                        S::Future: Send + 'static,
                    {
                        self.put_item = Some(::aws_smithy_legacy_http_server::routing::Route::new(svc));
                        self
                    }

/// Sets the [`UpdateItem`](crate::operation_shape::UpdateItem) operation.
                    ///
                    /// This should be an async function satisfying the [`Handler`](::aws_smithy_legacy_http_server::operation::Handler) trait.
                    /// See the [operation module documentation](::aws_smithy_legacy_http_server::operation) for more information.
                    ///
                    /// # Example
                    ///
                    /// ```no_run
                    /// use dynamodb_local_server_sdk::{DynamoDb20120810, DynamoDb20120810Config};
                    ///
                    /// use dynamodb_local_server_sdk::{input, output, error};
                    ///
                    /// async fn handler(input: input::UpdateItemInput) -> Result<output::UpdateItemOutput, error::UpdateItemError> {
///     todo!()
/// }
                    ///
                    /// let config = DynamoDb20120810Config::builder().build();
                    /// let app = DynamoDb20120810::builder(config)
                    ///     .update_item(handler)
                    ///     /* Set other handlers */
                    ///     .build()
                    ///     .unwrap();
                    /// # let app: DynamoDb20120810<::aws_smithy_legacy_http_server::routing::RoutingService<::aws_smithy_legacy_http_server::protocol::aws_json::router::AwsJsonRouter<::aws_smithy_legacy_http_server::routing::Route>, ::aws_smithy_legacy_http_server::protocol::aws_json_10::AwsJson1_0>> = app;
                    /// ```
                    ///
                    pub fn update_item<HandlerType, HandlerExtractors, UpgradeExtractors>(self, handler: HandlerType) -> Self
                    where
                        HandlerType: ::aws_smithy_legacy_http_server::operation::Handler<crate::operation_shape::UpdateItem, HandlerExtractors>,

                        ModelPl: ::aws_smithy_legacy_http_server::plugin::Plugin<
                            DynamoDb20120810<L>,
                            crate::operation_shape::UpdateItem,
                            ::aws_smithy_legacy_http_server::operation::IntoService<crate::operation_shape::UpdateItem, HandlerType>
                        >,
                        ::aws_smithy_legacy_http_server::operation::UpgradePlugin::<UpgradeExtractors>: ::aws_smithy_legacy_http_server::plugin::Plugin<
                            DynamoDb20120810<L>,
                            crate::operation_shape::UpdateItem,
                            ModelPl::Output
                        >,
                        HttpPl: ::aws_smithy_legacy_http_server::plugin::Plugin<
                            DynamoDb20120810<L>,
                            crate::operation_shape::UpdateItem,
                            <
                                ::aws_smithy_legacy_http_server::operation::UpgradePlugin::<UpgradeExtractors>
                                as ::aws_smithy_legacy_http_server::plugin::Plugin<
                                    DynamoDb20120810<L>,
                                    crate::operation_shape::UpdateItem,
                                    ModelPl::Output
                                >
                            >::Output
                        >,

                        HttpPl::Output: ::tower::Service<::http::Request<Body>, Response = ::http::Response<::aws_smithy_legacy_http_server::body::BoxBody>, Error = ::std::convert::Infallible> + Clone + Send + 'static,
                        <HttpPl::Output as ::tower::Service<::http::Request<Body>>>::Future: Send + 'static,

                    {
                        use ::aws_smithy_legacy_http_server::operation::OperationShapeExt;
                        use ::aws_smithy_legacy_http_server::plugin::Plugin;
                        let svc = crate::operation_shape::UpdateItem::from_handler(handler);
                        let svc = self.model_plugin.apply(svc);
                        let svc = ::aws_smithy_legacy_http_server::operation::UpgradePlugin::<UpgradeExtractors>::new().apply(svc);
                        let svc = self.http_plugin.apply(svc);
                        self.update_item_custom(svc)
                    }

                    /// Sets the [`UpdateItem`](crate::operation_shape::UpdateItem) operation.
                    ///
                    /// This should be an async function satisfying the [`Handler`](::aws_smithy_legacy_http_server::operation::Handler) trait.
                    /// See the [operation module documentation](::aws_smithy_legacy_http_server::operation) for more information.
                    ///
                    /// # Example
                    ///
                    /// ```no_run
                    /// use dynamodb_local_server_sdk::{DynamoDb20120810, DynamoDb20120810Config};
                    ///
                    /// use dynamodb_local_server_sdk::{input, output, error};
                    ///
                    /// async fn handler(input: input::UpdateItemInput) -> Result<output::UpdateItemOutput, error::UpdateItemError> {
///     todo!()
/// }
                    ///
                    /// let config = DynamoDb20120810Config::builder().build();
                    /// let svc = ::tower::util::service_fn(handler);
                    /// let app = DynamoDb20120810::builder(config)
                    ///     .update_item_service(svc)
                    ///     /* Set other handlers */
                    ///     .build()
                    ///     .unwrap();
                    /// # let app: DynamoDb20120810<::aws_smithy_legacy_http_server::routing::RoutingService<::aws_smithy_legacy_http_server::protocol::aws_json::router::AwsJsonRouter<::aws_smithy_legacy_http_server::routing::Route>, ::aws_smithy_legacy_http_server::protocol::aws_json_10::AwsJson1_0>> = app;
                    /// ```
                    ///
                    pub fn update_item_service<S, ServiceExtractors, UpgradeExtractors>(self, service: S) -> Self
                    where
                        S: ::aws_smithy_legacy_http_server::operation::OperationService<crate::operation_shape::UpdateItem, ServiceExtractors>,

                        ModelPl: ::aws_smithy_legacy_http_server::plugin::Plugin<
                            DynamoDb20120810<L>,
                            crate::operation_shape::UpdateItem,
                            ::aws_smithy_legacy_http_server::operation::Normalize<crate::operation_shape::UpdateItem, S>
                        >,
                        ::aws_smithy_legacy_http_server::operation::UpgradePlugin::<UpgradeExtractors>: ::aws_smithy_legacy_http_server::plugin::Plugin<
                            DynamoDb20120810<L>,
                            crate::operation_shape::UpdateItem,
                            ModelPl::Output
                        >,
                        HttpPl: ::aws_smithy_legacy_http_server::plugin::Plugin<
                            DynamoDb20120810<L>,
                            crate::operation_shape::UpdateItem,
                            <
                                ::aws_smithy_legacy_http_server::operation::UpgradePlugin::<UpgradeExtractors>
                                as ::aws_smithy_legacy_http_server::plugin::Plugin<
                                    DynamoDb20120810<L>,
                                    crate::operation_shape::UpdateItem,
                                    ModelPl::Output
                                >
                            >::Output
                        >,

                        HttpPl::Output: ::tower::Service<::http::Request<Body>, Response = ::http::Response<::aws_smithy_legacy_http_server::body::BoxBody>, Error = ::std::convert::Infallible> + Clone + Send + 'static,
                        <HttpPl::Output as ::tower::Service<::http::Request<Body>>>::Future: Send + 'static,

                    {
                        use ::aws_smithy_legacy_http_server::operation::OperationShapeExt;
                        use ::aws_smithy_legacy_http_server::plugin::Plugin;
                        let svc = crate::operation_shape::UpdateItem::from_service(service);
                        let svc = self.model_plugin.apply(svc);
                        let svc = ::aws_smithy_legacy_http_server::operation::UpgradePlugin::<UpgradeExtractors>::new().apply(svc);
                        let svc = self.http_plugin.apply(svc);
                        self.update_item_custom(svc)
                    }

                    /// Sets the [`UpdateItem`](crate::operation_shape::UpdateItem) to a custom [`Service`](tower::Service).
                    /// not constrained by the Smithy contract.
                    fn update_item_custom<S>(mut self, svc: S) -> Self
                    where
                        S: ::tower::Service<::http::Request<Body>, Response = ::http::Response<::aws_smithy_legacy_http_server::body::BoxBody>, Error = ::std::convert::Infallible> + Clone + Send + 'static,
                        S::Future: Send + 'static,
                    {
                        self.update_item = Some(::aws_smithy_legacy_http_server::routing::Route::new(svc));
                        self
                    }
                }

                impl<Body, L, HttpPl, ModelPl> DynamoDb20120810Builder<Body, L, HttpPl, ModelPl> {
                    /// Constructs a [`DynamoDb20120810`] from the arguments provided to the builder.
                ///
                /// Forgetting to register a handler for one or more operations will result in an error.
                ///
                /// Check out [`DynamoDb20120810Builder::build_unchecked`] if you'd prefer the service to return status code 500 when an
                /// unspecified route is requested.
                pub fn build(self) -> ::std::result::Result<
                    DynamoDb20120810<
                        ::aws_smithy_legacy_http_server::routing::RoutingService<
                            ::aws_smithy_legacy_http_server::protocol::aws_json::router::AwsJsonRouter<L::Service>,
                            ::aws_smithy_legacy_http_server::protocol::aws_json_10::AwsJson1_0,
                        >,
                    >,
                    MissingOperationsError,
                >
                where
                    L: ::tower::Layer<::aws_smithy_legacy_http_server::routing::Route<Body>>,
                {
                    let router = {
                        use ::aws_smithy_legacy_http_server::operation::OperationShape;
                        let mut missing_operation_names = std::collections::HashMap::new();
                        if self.create_table.is_none() {
                                missing_operation_names.insert(crate::operation_shape::CreateTable::ID, ".create_table()");
                            }
if self.get_item.is_none() {
                                missing_operation_names.insert(crate::operation_shape::GetItem::ID, ".get_item()");
                            }
if self.put_item.is_none() {
                                missing_operation_names.insert(crate::operation_shape::PutItem::ID, ".put_item()");
                            }
if self.update_item.is_none() {
                                missing_operation_names.insert(crate::operation_shape::UpdateItem::ID, ".update_item()");
                            }
                        if !missing_operation_names.is_empty() {
                            return Err(MissingOperationsError {
                                operation_names2setter_methods: missing_operation_names,
                            });
                        }
                        let unexpected_error_msg = "this should never panic since we are supposed to check beforehand that a handler has been registered for this operation; please file a bug report under https://github.com/smithy-lang/smithy-rs/issues";

                        

                        ::aws_smithy_legacy_http_server::protocol::aws_json::router::AwsJsonRouter::from_iter([(request_specs::create_table(), self.create_table.expect(unexpected_error_msg)),
(request_specs::get_item(), self.get_item.expect(unexpected_error_msg)),
(request_specs::put_item(), self.put_item.expect(unexpected_error_msg)),
(request_specs::update_item(), self.update_item.expect(unexpected_error_msg)),])
                    };
                    let svc = ::aws_smithy_legacy_http_server::routing::RoutingService::new(router);
                    let svc = svc.map(|s| s.layer(self.layer));
                    Ok(DynamoDb20120810 { svc })
                }

                    /// Constructs a [`DynamoDb20120810`] from the arguments provided to the builder.
                /// Operations without a handler default to returning 500 Internal Server Error to the caller.
                ///
                /// Check out [`DynamoDb20120810Builder::build`] if you'd prefer the builder to fail if one or more operations do
                /// not have a registered handler.
                pub fn build_unchecked(self) -> DynamoDb20120810<L::Service>
                where
                    Body: Send + 'static,
                    L: ::tower::Layer<
                        ::aws_smithy_legacy_http_server::routing::RoutingService<::aws_smithy_legacy_http_server::protocol::aws_json::router::AwsJsonRouter<::aws_smithy_legacy_http_server::routing::Route<Body>>, ::aws_smithy_legacy_http_server::protocol::aws_json_10::AwsJson1_0>
                    >
                {
                    let router = ::aws_smithy_legacy_http_server::protocol::aws_json::router::AwsJsonRouter::from_iter([(
                                request_specs::create_table(),
                                self.create_table.unwrap_or_else(|| {
                                    let svc = ::aws_smithy_legacy_http_server::operation::MissingFailure::<::aws_smithy_legacy_http_server::protocol::aws_json_10::AwsJson1_0>::default();
                                    ::aws_smithy_legacy_http_server::routing::Route::new(svc)
                                })
                            ),
(
                                request_specs::get_item(),
                                self.get_item.unwrap_or_else(|| {
                                    let svc = ::aws_smithy_legacy_http_server::operation::MissingFailure::<::aws_smithy_legacy_http_server::protocol::aws_json_10::AwsJson1_0>::default();
                                    ::aws_smithy_legacy_http_server::routing::Route::new(svc)
                                })
                            ),
(
                                request_specs::put_item(),
                                self.put_item.unwrap_or_else(|| {
                                    let svc = ::aws_smithy_legacy_http_server::operation::MissingFailure::<::aws_smithy_legacy_http_server::protocol::aws_json_10::AwsJson1_0>::default();
                                    ::aws_smithy_legacy_http_server::routing::Route::new(svc)
                                })
                            ),
(
                                request_specs::update_item(),
                                self.update_item.unwrap_or_else(|| {
                                    let svc = ::aws_smithy_legacy_http_server::operation::MissingFailure::<::aws_smithy_legacy_http_server::protocol::aws_json_10::AwsJson1_0>::default();
                                    ::aws_smithy_legacy_http_server::routing::Route::new(svc)
                                })
                            ),]);
                    let svc = self
                        .layer
                        .layer(::aws_smithy_legacy_http_server::routing::RoutingService::new(router));
                    DynamoDb20120810 { svc }
                }
                }

            /// The error encountered when calling the [`DynamoDb20120810Builder::build`] method if one or more operation handlers are not
                /// specified.
                #[derive(Debug)]
                pub struct MissingOperationsError {
                    operation_names2setter_methods: std::collections::HashMap<::aws_smithy_legacy_http_server::shape_id::ShapeId, &'static str>,
                }

                impl std::fmt::Display for MissingOperationsError {
                    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                        write!(
                            f,
                            "You must specify a handler for all operations attached to `DynamoDb20120810`.\n\
                            We are missing handlers for the following operations:\n",
                        )?;
                        for operation_name in self.operation_names2setter_methods.keys() {
                            writeln!(f, "- {}", operation_name.absolute())?;
                        }

                        writeln!(f, "\nUse the dedicated methods on `DynamoDb20120810Builder` to register the missing handlers:")?;
                        for setter_name in self.operation_names2setter_methods.values() {
                            writeln!(f, "- {}", setter_name)?;
                        }
                        Ok(())
                    }
                }

                impl std::error::Error for MissingOperationsError {}

            mod request_specs {
                    pub(super) fn create_table() -> &'static str {
                            "DynamoDB_20120810.CreateTable"
                        }
pub(super) fn get_item() -> &'static str {
                            "DynamoDB_20120810.GetItem"
                        }
pub(super) fn put_item() -> &'static str {
                            "DynamoDB_20120810.PutItem"
                        }
pub(super) fn update_item() -> &'static str {
                            "DynamoDB_20120810.UpdateItem"
                        }
                }

            #[allow(missing_docs)] // documentation missing in model
///
                /// See the [root](crate) documentation for more information.
                #[derive(Clone)]
                pub struct DynamoDb20120810<
                    S = ::aws_smithy_legacy_http_server::routing::RoutingService<
                        ::aws_smithy_legacy_http_server::protocol::aws_json::router::AwsJsonRouter<
                            ::aws_smithy_legacy_http_server::routing::Route<
                                ::aws_smithy_legacy_http_server::body::BoxBody
                            >,
                        >,
                        ::aws_smithy_legacy_http_server::protocol::aws_json_10::AwsJson1_0,
                    >
                > {
                    // This is the router wrapped by layers.
                    svc: S,
                }

                impl DynamoDb20120810<()> {
                    /// Constructs a builder for [`DynamoDb20120810`].
                    /// You must specify a configuration object holding any plugins and layers that should be applied
                    /// to the operations in this service.
                    pub fn builder<
                        Body,
                        L,
                        HttpPl: ::aws_smithy_legacy_http_server::plugin::HttpMarker,
                        ModelPl: ::aws_smithy_legacy_http_server::plugin::ModelMarker,
                    >(
                        config: DynamoDb20120810Config<L, HttpPl, ModelPl>,
                    ) -> DynamoDb20120810Builder<Body, L, HttpPl, ModelPl> {
                        DynamoDb20120810Builder {
                            create_table: None
, get_item: None
, put_item: None
, update_item: None,
                            layer: config.layers,
                            http_plugin: config.http_plugins,
                            model_plugin: config.model_plugins,
                        }
                    }

                    /// Constructs a builder for [`DynamoDb20120810`].
                    /// You must specify what plugins should be applied to the operations in this service.
                    ///
                    /// Use [`DynamoDb20120810::builder_without_plugins`] if you don't need to apply plugins.
                    ///
                    /// Check out [`HttpPlugins`](::aws_smithy_legacy_http_server::plugin::HttpPlugins) and
                    /// [`ModelPlugins`](::aws_smithy_legacy_http_server::plugin::ModelPlugins) if you need to apply
                    /// multiple plugins.
                    #[deprecated(
                        since = "0.57.0",
                        note = "please use the `builder` constructor and register plugins on the `DynamoDb20120810Config` object instead; see https://github.com/smithy-lang/smithy-rs/discussions/3096"
                    )]
                    pub fn builder_with_plugins<
                        Body,
                        HttpPl: ::aws_smithy_legacy_http_server::plugin::HttpMarker,
                        ModelPl: ::aws_smithy_legacy_http_server::plugin::ModelMarker
                    >(
                        http_plugin: HttpPl,
                        model_plugin: ModelPl
                    ) -> DynamoDb20120810Builder<Body, ::tower::layer::util::Identity, HttpPl, ModelPl> {
                        DynamoDb20120810Builder {
                            create_table: None
, get_item: None
, put_item: None
, update_item: None,
                            layer: ::tower::layer::util::Identity::new(),
                            http_plugin,
                            model_plugin
                        }
                    }

                    /// Constructs a builder for [`DynamoDb20120810`].
                    ///
                    /// Use [`DynamoDb20120810::builder_with_plugins`] if you need to specify plugins.
                    #[deprecated(
                        since = "0.57.0",
                        note = "please use the `builder` constructor instead; see https://github.com/smithy-lang/smithy-rs/discussions/3096"
                    )]
                    pub fn builder_without_plugins<Body>() -> DynamoDb20120810Builder<
                        Body,
                        ::tower::layer::util::Identity,
                        ::aws_smithy_legacy_http_server::plugin::IdentityPlugin,
                        ::aws_smithy_legacy_http_server::plugin::IdentityPlugin
                    > {
                        Self::builder_with_plugins(::aws_smithy_legacy_http_server::plugin::IdentityPlugin, ::aws_smithy_legacy_http_server::plugin::IdentityPlugin)
                    }
                }

                impl<S> DynamoDb20120810<S> {
                    /// Converts [`DynamoDb20120810`] into a [`MakeService`](tower::make::MakeService).
                    pub fn into_make_service(self) -> ::aws_smithy_legacy_http_server::routing::IntoMakeService<Self> {
                        ::aws_smithy_legacy_http_server::routing::IntoMakeService::new(self)
                    }


                    /// Converts [`DynamoDb20120810`] into a [`MakeService`](tower::make::MakeService) with [`ConnectInfo`](::aws_smithy_legacy_http_server::request::connect_info::ConnectInfo).
                    pub fn into_make_service_with_connect_info<C>(self) -> ::aws_smithy_legacy_http_server::routing::IntoMakeServiceWithConnectInfo<Self, C> {
                        ::aws_smithy_legacy_http_server::routing::IntoMakeServiceWithConnectInfo::new(self)
                    }
                }

                impl<S>
                    DynamoDb20120810<
                        ::aws_smithy_legacy_http_server::routing::RoutingService<
                            ::aws_smithy_legacy_http_server::protocol::aws_json::router::AwsJsonRouter<S>,
                            ::aws_smithy_legacy_http_server::protocol::aws_json_10::AwsJson1_0,
                        >,
                    >
                {
                    /// Applies a [`Layer`](::tower::Layer) uniformly to all routes.
                    #[deprecated(
                        since = "0.57.0",
                        note = "please add layers to the `DynamoDb20120810Config` object instead; see https://github.com/smithy-lang/smithy-rs/discussions/3096"
                    )]
                    pub fn layer<L>(
                        self,
                        layer: &L,
                    ) -> DynamoDb20120810<
                        ::aws_smithy_legacy_http_server::routing::RoutingService<
                            ::aws_smithy_legacy_http_server::protocol::aws_json::router::AwsJsonRouter<L::Service>,
                            ::aws_smithy_legacy_http_server::protocol::aws_json_10::AwsJson1_0,
                        >,
                    >
                    where
                        L: ::tower::Layer<S>,
                    {
                        DynamoDb20120810 {
                            svc: self.svc.map(|s| s.layer(layer)),
                        }
                    }

                    /// Applies [`Route::new`](::aws_smithy_legacy_http_server::routing::Route::new) to all routes.
                    ///
                    /// This has the effect of erasing all types accumulated via layers.
                    pub fn boxed<B>(
                        self,
                    ) -> DynamoDb20120810<
                        ::aws_smithy_legacy_http_server::routing::RoutingService<
                            ::aws_smithy_legacy_http_server::protocol::aws_json::router::AwsJsonRouter<
                                ::aws_smithy_legacy_http_server::routing::Route<B>,
                            >,
                            ::aws_smithy_legacy_http_server::protocol::aws_json_10::AwsJson1_0,
                        >,
                    >
                    where
                        S: ::tower::Service<
                            ::http::Request<B>,
                            Response = ::http::Response<::aws_smithy_legacy_http_server::body::BoxBody>,
                            Error = std::convert::Infallible,
                        >,
                        S: Clone + Send + 'static,
                        S::Future: Send + 'static,
                    {
                        self.layer(&::tower::layer::layer_fn(
                            ::aws_smithy_legacy_http_server::routing::Route::new,
                        ))
                    }
                }

                impl<S, R> ::tower::Service<R> for DynamoDb20120810<S>
                where
                    S: ::tower::Service<R>,
                {
                    type Response = S::Response;
                    type Error = S::Error;
                    type Future = S::Future;

                    fn poll_ready(&mut self, cx: &mut std::task::Context) -> std::task::Poll<::std::result::Result<(), Self::Error>> {
                        self.svc.poll_ready(cx)
                    }

                    fn call(&mut self, request: R) -> Self::Future {
                        self.svc.call(request)
                    }
                }

            /// An enumeration of all [operations](https://smithy.io/2.0/spec/service-types.html#operation) in DynamoDb20120810.
                #[allow(clippy::enum_variant_names)]
                #[derive(Debug, PartialEq, Eq, Clone, Copy)]
                pub enum Operation {
                    CreateTable,GetItem,PutItem,UpdateItem
                }

                impl Operation {
                    /// Returns the [operations](https://smithy.io/2.0/spec/service-types.html#operation) [`ShapeId`](::aws_smithy_legacy_http_server::shape_id::ShapeId).
                    pub fn shape_id(&self) -> ::aws_smithy_legacy_http_server::shape_id::ShapeId {
                        match self {
                            Operation::CreateTable => ::aws_smithy_legacy_http_server::shape_id::ShapeId::new("com.amazonaws.dynamodb#CreateTable", "com.amazonaws.dynamodb", "CreateTable")
,Operation::GetItem => ::aws_smithy_legacy_http_server::shape_id::ShapeId::new("com.amazonaws.dynamodb#GetItem", "com.amazonaws.dynamodb", "GetItem")
,Operation::PutItem => ::aws_smithy_legacy_http_server::shape_id::ShapeId::new("com.amazonaws.dynamodb#PutItem", "com.amazonaws.dynamodb", "PutItem")
,Operation::UpdateItem => ::aws_smithy_legacy_http_server::shape_id::ShapeId::new("com.amazonaws.dynamodb#UpdateItem", "com.amazonaws.dynamodb", "UpdateItem")
                        }
                    }
                }
impl<L> ::aws_smithy_legacy_http_server::service::ContainsOperation<crate::operation_shape::CreateTable>
                        for DynamoDb20120810<L>
                    {
                        const VALUE: Operation = Operation::CreateTable;
                    }
impl<L> ::aws_smithy_legacy_http_server::service::ContainsOperation<crate::operation_shape::GetItem>
                        for DynamoDb20120810<L>
                    {
                        const VALUE: Operation = Operation::GetItem;
                    }
impl<L> ::aws_smithy_legacy_http_server::service::ContainsOperation<crate::operation_shape::PutItem>
                        for DynamoDb20120810<L>
                    {
                        const VALUE: Operation = Operation::PutItem;
                    }
impl<L> ::aws_smithy_legacy_http_server::service::ContainsOperation<crate::operation_shape::UpdateItem>
                        for DynamoDb20120810<L>
                    {
                        const VALUE: Operation = Operation::UpdateItem;
                    }

            impl<S> ::aws_smithy_legacy_http_server::service::ServiceShape for DynamoDb20120810<S> {
                    const ID: ::aws_smithy_legacy_http_server::shape_id::ShapeId = ::aws_smithy_legacy_http_server::shape_id::ShapeId::new("com.amazonaws.dynamodb#DynamoDB_20120810", "com.amazonaws.dynamodb", "DynamoDB_20120810");

                    const VERSION: Option<&'static str> = Some("2012-08-10");

                    type Protocol = ::aws_smithy_legacy_http_server::protocol::aws_json_10::AwsJson1_0;

                    type Operations = Operation;
                }
/// Configuration for the [`DynamoDb20120810`]. This is the central place where to register and
            /// configure [`::tower::Layer`]s, HTTP plugins, and model plugins.
            ///
            /// ```rust,no_run
            /// # use dynamodb_local_server_sdk::DynamoDb20120810Config;
            /// # use ::aws_smithy_legacy_http_server::plugin::IdentityPlugin;
            /// # use ::tower::layer::util::Identity;
            /// # let authentication_plugin = IdentityPlugin;
            /// # let authorization_plugin = IdentityPlugin;
            /// # let server_request_id_provider_layer = Identity::new();
            /// let config = DynamoDb20120810Config::builder()
            ///     // Layers get executed first...
            ///     .layer(server_request_id_provider_layer)
            ///     // ...then HTTP plugins...
            ///     .http_plugin(authentication_plugin)
            ///     // ...and right after deserialization, model plugins.
            ///     .model_plugin(authorization_plugin)
            ///     .build();
            /// ```
            ///
            /// See the [`plugin`] system for details.
            ///
            /// [`plugin`]: ::aws_smithy_legacy_http_server::plugin
            #[derive(::std::fmt::Debug)]
            pub struct DynamoDb20120810Config<L, H, M> {
                layers: L,
                http_plugins: H,
                model_plugins: M,
            }

            impl DynamoDb20120810Config<(), (), ()> {
                /// Returns a builder to construct the configuration.
                pub fn builder() -> DynamoDb20120810ConfigBuilder<
                    ::tower::layer::util::Identity,
                    ::aws_smithy_legacy_http_server::plugin::IdentityPlugin,
                    ::aws_smithy_legacy_http_server::plugin::IdentityPlugin,
                > {
                    DynamoDb20120810ConfigBuilder {
                        layers: ::tower::layer::util::Identity::new(),
                        http_plugins: ::aws_smithy_legacy_http_server::plugin::IdentityPlugin,
                        model_plugins: ::aws_smithy_legacy_http_server::plugin::IdentityPlugin,
                        
                    }
                }
            }

            /// Builder returned by [`DynamoDb20120810Config::builder()`].
            #[derive(::std::fmt::Debug)]
            pub struct DynamoDb20120810ConfigBuilder<L, H, M> {
                pub(crate) layers: L,
                pub(crate) http_plugins: H,
                pub(crate) model_plugins: M,
                
            }

            

            impl<L, H, M> DynamoDb20120810ConfigBuilder<L, H, M> {
                

                /// Add a [`::tower::Layer`] to the service.
                pub fn layer<NewLayer>(self, layer: NewLayer) -> DynamoDb20120810ConfigBuilder<::tower::layer::util::Stack<NewLayer, L>, H, M> {
                    DynamoDb20120810ConfigBuilder {
                        layers: ::tower::layer::util::Stack::new(layer, self.layers),
                        http_plugins: self.http_plugins,
                        model_plugins: self.model_plugins,
                        
                    }
                }

                /// Add a HTTP [plugin] to the service.
                ///
                /// [plugin]: ::aws_smithy_legacy_http_server::plugin
                // We eagerly require `NewPlugin: HttpMarker`, despite not really needing it, because compiler
                // errors get _substantially_ better if the user makes a mistake.
                pub fn http_plugin<NewPlugin: ::aws_smithy_legacy_http_server::plugin::HttpMarker>(
                    self,
                    http_plugin: NewPlugin,
                ) -> DynamoDb20120810ConfigBuilder<L, ::aws_smithy_legacy_http_server::plugin::PluginStack<NewPlugin, H>, M> {
                    DynamoDb20120810ConfigBuilder {
                        layers: self.layers,
                        http_plugins: ::aws_smithy_legacy_http_server::plugin::PluginStack::new(http_plugin, self.http_plugins),
                        model_plugins: self.model_plugins,
                        
                    }
                }

                /// Add a model [plugin] to the service.
                ///
                /// [plugin]: ::aws_smithy_legacy_http_server::plugin
                // We eagerly require `NewPlugin: ModelMarker`, despite not really needing it, because compiler
                // errors get _substantially_ better if the user makes a mistake.
                pub fn model_plugin<NewPlugin: ::aws_smithy_legacy_http_server::plugin::ModelMarker>(
                    self,
                    model_plugin: NewPlugin,
                ) -> DynamoDb20120810ConfigBuilder<L, H, ::aws_smithy_legacy_http_server::plugin::PluginStack<NewPlugin, M>> {
                    DynamoDb20120810ConfigBuilder {
                        layers: self.layers,
                        http_plugins: self.http_plugins,
                        model_plugins: ::aws_smithy_legacy_http_server::plugin::PluginStack::new(model_plugin, self.model_plugins),
                        
                    }
                }

                /// Build the configuration.
                pub fn build(self) -> super::DynamoDb20120810Config<L, H, M> {
    
    super::DynamoDb20120810Config {
                                layers: self.layers,
                                http_plugins: self.http_plugins,
                                model_plugins: self.model_plugins,
                            }
}
            }
/// A macro to help with scoping [plugins](crate::server::plugin) to a subset of all operations.
                ///
                /// In contrast to [`crate::server::scope`](crate::server::scope), this macro has knowledge
                /// of the service and any operations _not_ specified will be placed in the opposing group.
                ///
                /// # Example
                ///
                /// ```rust
                /// scope! {
                ///     /// Includes [`CreateTable`], excluding all other operations.
                ///     struct ScopeA {
                ///         includes: [CreateTable]
                ///     }
                /// }
                ///
                /// scope! {
                ///     /// Excludes [`CreateTable`], excluding all other operations.
                ///     struct ScopeB {
                ///         excludes: [CreateTable]
                ///     }
                /// }
                ///
                /// # use dynamodb_local_server_sdk::server::plugin::{Plugin, Scoped};
                /// # use dynamodb_local_server_sdk::scope;
                /// # struct MockPlugin;
                /// # impl<S, Op, T> Plugin<S, Op, T> for MockPlugin { type Output = u32; fn apply(&self, input: T) -> u32 { 3 } }
                /// # let scoped_a = Scoped::new::<ScopeA>(MockPlugin);
                /// # let scoped_b = Scoped::new::<ScopeB>(MockPlugin);
                /// # let a = Plugin::<(), dynamodb_local_server_sdk::operation_shape::CreateTable, u64>::apply(&scoped_a, 6);
                /// # let b = Plugin::<(), dynamodb_local_server_sdk::operation_shape::CreateTable, u64>::apply(&scoped_b, 6);
                /// # assert_eq!(a, 3_u32);
                /// # assert_eq!(b, 6_u64);
                /// ```
                #[macro_export]
                macro_rules! scope {
                    // Completed, render impls
                    (@ $ name: ident, $ contains: ident () ($($ temp: ident)*) ($($ not_member: ident)*)) => {
                        $(
                            impl $ crate::server::plugin::scoped::Membership<$ temp> for $ name {
                                type Contains = $ crate::server::plugin::scoped::$ contains;
                            }
                        )*
                        $(
                            impl $ crate::server::plugin::scoped::Membership<$ not_member> for $ name {
                                type Contains = $ crate::server::plugin::scoped::$ contains;
                            }
                        )*
                    };
                    // All `not_member`s exhausted, move `temp` into `not_member`
                    (@ $ name: ident, $ contains: ident ($($ member: ident)*) ($($ temp: ident)*) ()) => {
                        scope! { @ $ name, $ contains ($($ member)*) () ($($ temp)*) }
                    };
                    
                        // CreateTable match found, pop from both `member` and `not_member`
                        (@ $ name: ident, $ contains: ident (CreateTable $($ member: ident)*) ($($ temp: ident)*) (CreateTable $($ not_member: ident)*)) => {
                            scope! { @ $ name, $ contains ($($ member)*) ($($ temp)*) ($($ not_member)*) }
                        };
                        // CreateTable match not found, pop from `not_member` into `temp` stack
                        (@ $ name: ident, $ contains: ident (CreateTable $($ member: ident)*) ($($ temp: ident)*) ($ other: ident $($ not_member: ident)*)) => {
                            scope! { @ $ name, $ contains (CreateTable $($ member)*) ($ other $($ temp)*) ($($ not_member)*) }
                        };
                        
                        // GetItem match found, pop from both `member` and `not_member`
                        (@ $ name: ident, $ contains: ident (GetItem $($ member: ident)*) ($($ temp: ident)*) (GetItem $($ not_member: ident)*)) => {
                            scope! { @ $ name, $ contains ($($ member)*) ($($ temp)*) ($($ not_member)*) }
                        };
                        // GetItem match not found, pop from `not_member` into `temp` stack
                        (@ $ name: ident, $ contains: ident (GetItem $($ member: ident)*) ($($ temp: ident)*) ($ other: ident $($ not_member: ident)*)) => {
                            scope! { @ $ name, $ contains (GetItem $($ member)*) ($ other $($ temp)*) ($($ not_member)*) }
                        };
                        
                        // PutItem match found, pop from both `member` and `not_member`
                        (@ $ name: ident, $ contains: ident (PutItem $($ member: ident)*) ($($ temp: ident)*) (PutItem $($ not_member: ident)*)) => {
                            scope! { @ $ name, $ contains ($($ member)*) ($($ temp)*) ($($ not_member)*) }
                        };
                        // PutItem match not found, pop from `not_member` into `temp` stack
                        (@ $ name: ident, $ contains: ident (PutItem $($ member: ident)*) ($($ temp: ident)*) ($ other: ident $($ not_member: ident)*)) => {
                            scope! { @ $ name, $ contains (PutItem $($ member)*) ($ other $($ temp)*) ($($ not_member)*) }
                        };
                        
                        // UpdateItem match found, pop from both `member` and `not_member`
                        (@ $ name: ident, $ contains: ident (UpdateItem $($ member: ident)*) ($($ temp: ident)*) (UpdateItem $($ not_member: ident)*)) => {
                            scope! { @ $ name, $ contains ($($ member)*) ($($ temp)*) ($($ not_member)*) }
                        };
                        // UpdateItem match not found, pop from `not_member` into `temp` stack
                        (@ $ name: ident, $ contains: ident (UpdateItem $($ member: ident)*) ($($ temp: ident)*) ($ other: ident $($ not_member: ident)*)) => {
                            scope! { @ $ name, $ contains (UpdateItem $($ member)*) ($ other $($ temp)*) ($($ not_member)*) }
                        };
                        
                    (
                        $(#[$ attrs:meta])*
                        $ vis:vis struct $ name:ident {
                            includes: [$($ include:ident),*]
                        }
                    ) => {
                        use $ crate::operation_shape::*;
                        $ crate::server::scope! {
                            $(#[$ attrs])*
                            $ vis struct $ name {
                                includes: [$($ include),*],
                                excludes: []
                            }
                        }
                        scope! { @ $ name, False ($($ include)*) () (CreateTable GetItem PutItem UpdateItem) }
                    };
                    (
                        $(#[$ attrs:meta])*
                        $ vis:vis struct $ name:ident {
                            excludes: [$($ exclude:ident),*]
                        }
                    ) => {
                        use $ crate::operation_shape::*;

                        $ crate::server::scope! {
                            $(#[$ attrs])*
                            $ vis struct $ name {
                                includes: [],
                                excludes: [$($ exclude),*]
                            }
                        }
                        scope! { @ $ name, True ($($ exclude)*) () (CreateTable GetItem PutItem UpdateItem) }
                    };
                }

