// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_restore_summary(
    object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
    input: &crate::model::RestoreSummary,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    if let Some(var_1) = &input.source_backup_arn {
        object.key("SourceBackupArn").string(var_1.as_str());
    }
    if let Some(var_2) = &input.source_table_arn {
        object.key("SourceTableArn").string(var_2.as_str());
    }
    {
        object.key("RestoreDateTime").date_time(
            &input.restore_date_time,
            ::aws_smithy_types::date_time::Format::EpochSeconds,
        )?;
    }
    {
        object
            .key("RestoreInProgress")
            .boolean(input.restore_in_progress);
    }
    Ok(())
}
