// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_archival_summary(
                         object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
                         input: &crate::model::ArchivalSummary,
                    ) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    if let Some(var_1) = &input.archival_date_time {
        object.key("ArchivalDateTime").date_time(var_1, ::aws_smithy_types::date_time::Format::EpochSeconds)?;
    }
    if let Some(var_2) = &input.archival_reason {
        object.key("ArchivalReason").string(var_2.as_str());
    }
    if let Some(var_3) = &input.archival_backup_arn {
        object.key("ArchivalBackupArn").string(var_3.as_str());
    }
    Ok(())
}

