// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_provisioned_throughput_override(
                         object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
                         input: &crate::model::ProvisionedThroughputOverride,
                    ) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    if let Some(var_1) = &input.read_capacity_units {
        object.key("ReadCapacityUnits").number(#[allow(clippy::useless_conversion)]::aws_smithy_types::Number::NegInt((*var_1).into()));
    }
    Ok(())
}

