// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_create_table_output_output_output(
    value: &crate::output::CreateTableOutput,
) -> ::std::result::Result<String, ::aws_smithy_types::error::operation::SerializationError> {
    let mut out = ::std::string::String::new();
    let mut object = ::aws_smithy_json::serialize::JsonObjectWriter::new(&mut out);
    crate::protocol_serde::shape_create_table_output::ser_create_table_output_output(
        &mut object,
        value,
    )?;
    object.finish();
    Ok(out)
}

pub fn ser_create_table_output_output(
    object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
    input: &crate::output::CreateTableOutput,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    if let Some(var_1) = &input.table_description {
        #[allow(unused_mut)]
        let mut object_2 = object.key("TableDescription").start_object();
        crate::protocol_serde::shape_table_description::ser_table_description(
            &mut object_2,
            var_1,
        )?;
        object_2.finish();
    }
    Ok(())
}
