// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_conditional_check_failed_exception_error(value: &crate::error::ConditionalCheckFailedException) -> ::std::result::Result<String, ::aws_smithy_types::error::operation::SerializationError> {
    let mut out = ::std::string::String::new();
                        let mut object = ::aws_smithy_json::serialize::JsonObjectWriter::new(&mut out);
    crate::protocol_serde::shape_conditional_check_failed_exception::ser_conditional_check_failed_exception(&mut object, value)?;
    object.key("__type").string("com.amazonaws.dynamodb#ConditionalCheckFailedException");
    object.finish();
                        Ok(out)
}

pub fn ser_conditional_check_failed_exception(
                         object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
                         input: &crate::error::ConditionalCheckFailedException,
                    ) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    if let Some(var_1) = &input.message {
        object.key("message").string(var_1.as_str());
    }
    if let Some(var_2) = &input.item {
        #[allow(unused_mut)]
        let mut object_3 = object.key("Item").start_object();
        for (key_4, value_5) in var_2 {
             {
                #[allow(unused_mut)]
                let mut object_6 = object_3.key(key_4.as_str()).start_object();
                crate::protocol_serde::shape_attribute_value::ser_attribute_value(&mut object_6, value_5)?;
                object_6.finish();
            }
        }
        object_3.finish();
    }
    Ok(())
}

