// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_table_description(
                         object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
                         input: &crate::model::TableDescription,
                    ) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    if let Some(var_1) = &input.attribute_definitions {
        let mut array_2 = object.key("AttributeDefinitions").start_array();
        for item_3 in var_1 {
             {
                #[allow(unused_mut)]
                let mut object_4 = array_2.value().start_object();
                crate::protocol_serde::shape_attribute_definition::ser_attribute_definition(&mut object_4, item_3)?;
                object_4.finish();
            }
        }
        array_2.finish();
    }
    if let Some(var_5) = &input.table_name {
        object.key("TableName").string(var_5.as_str());
    }
    if let Some(var_6) = &input.key_schema {
        let mut array_7 = object.key("KeySchema").start_array();
        for item_8 in var_6 {
             {
                #[allow(unused_mut)]
                let mut object_9 = array_7.value().start_object();
                crate::protocol_serde::shape_key_schema_element::ser_key_schema_element(&mut object_9, item_8)?;
                object_9.finish();
            }
        }
        array_7.finish();
    }
    if let Some(var_10) = &input.table_status {
        object.key("TableStatus").string(var_10.as_str());
    }
    if let Some(var_11) = &input.creation_date_time {
        object.key("CreationDateTime").date_time(var_11, ::aws_smithy_types::date_time::Format::EpochSeconds)?;
    }
    if let Some(var_12) = &input.provisioned_throughput {
        #[allow(unused_mut)]
        let mut object_13 = object.key("ProvisionedThroughput").start_object();
        crate::protocol_serde::shape_provisioned_throughput_description::ser_provisioned_throughput_description(&mut object_13, var_12)?;
        object_13.finish();
    }
    if let Some(var_14) = &input.table_size_bytes {
        object.key("TableSizeBytes").number(#[allow(clippy::useless_conversion)]::aws_smithy_types::Number::NegInt((*var_14).into()));
    }
    if let Some(var_15) = &input.item_count {
        object.key("ItemCount").number(#[allow(clippy::useless_conversion)]::aws_smithy_types::Number::NegInt((*var_15).into()));
    }
    if let Some(var_16) = &input.table_arn {
        object.key("TableArn").string(var_16.as_str());
    }
    if let Some(var_17) = &input.table_id {
        object.key("TableId").string(var_17.as_str());
    }
    if let Some(var_18) = &input.billing_mode_summary {
        #[allow(unused_mut)]
        let mut object_19 = object.key("BillingModeSummary").start_object();
        crate::protocol_serde::shape_billing_mode_summary::ser_billing_mode_summary(&mut object_19, var_18)?;
        object_19.finish();
    }
    if let Some(var_20) = &input.local_secondary_indexes {
        let mut array_21 = object.key("LocalSecondaryIndexes").start_array();
        for item_22 in var_20 {
             {
                #[allow(unused_mut)]
                let mut object_23 = array_21.value().start_object();
                crate::protocol_serde::shape_local_secondary_index_description::ser_local_secondary_index_description(&mut object_23, item_22)?;
                object_23.finish();
            }
        }
        array_21.finish();
    }
    if let Some(var_24) = &input.global_secondary_indexes {
        let mut array_25 = object.key("GlobalSecondaryIndexes").start_array();
        for item_26 in var_24 {
             {
                #[allow(unused_mut)]
                let mut object_27 = array_25.value().start_object();
                crate::protocol_serde::shape_global_secondary_index_description::ser_global_secondary_index_description(&mut object_27, item_26)?;
                object_27.finish();
            }
        }
        array_25.finish();
    }
    if let Some(var_28) = &input.stream_specification {
        #[allow(unused_mut)]
        let mut object_29 = object.key("StreamSpecification").start_object();
        crate::protocol_serde::shape_stream_specification::ser_stream_specification(&mut object_29, var_28)?;
        object_29.finish();
    }
    if let Some(var_30) = &input.latest_stream_label {
        object.key("LatestStreamLabel").string(var_30.as_str());
    }
    if let Some(var_31) = &input.latest_stream_arn {
        object.key("LatestStreamArn").string(var_31.as_str());
    }
    if let Some(var_32) = &input.global_table_version {
        object.key("GlobalTableVersion").string(var_32.as_str());
    }
    if let Some(var_33) = &input.replicas {
        let mut array_34 = object.key("Replicas").start_array();
        for item_35 in var_33 {
             {
                #[allow(unused_mut)]
                let mut object_36 = array_34.value().start_object();
                crate::protocol_serde::shape_replica_description::ser_replica_description(&mut object_36, item_35)?;
                object_36.finish();
            }
        }
        array_34.finish();
    }
    if let Some(var_37) = &input.restore_summary {
        #[allow(unused_mut)]
        let mut object_38 = object.key("RestoreSummary").start_object();
        crate::protocol_serde::shape_restore_summary::ser_restore_summary(&mut object_38, var_37)?;
        object_38.finish();
    }
    if let Some(var_39) = &input.sse_description {
        #[allow(unused_mut)]
        let mut object_40 = object.key("SSEDescription").start_object();
        crate::protocol_serde::shape_sse_description::ser_sse_description(&mut object_40, var_39)?;
        object_40.finish();
    }
    if let Some(var_41) = &input.archival_summary {
        #[allow(unused_mut)]
        let mut object_42 = object.key("ArchivalSummary").start_object();
        crate::protocol_serde::shape_archival_summary::ser_archival_summary(&mut object_42, var_41)?;
        object_42.finish();
    }
    Ok(())
}

