// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_get_item_output_output_output(
    value: &crate::output::GetItemOutput,
) -> ::std::result::Result<String, ::aws_smithy_types::error::operation::SerializationError> {
    let mut out = ::std::string::String::new();
    let mut object = ::aws_smithy_json::serialize::JsonObjectWriter::new(&mut out);
    crate::protocol_serde::shape_get_item_output::ser_get_item_output_output(&mut object, value)?;
    object.finish();
    Ok(out)
}

pub fn ser_get_item_output_output(
    object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
    input: &crate::output::GetItemOutput,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    if let Some(var_1) = &input.item {
        #[allow(unused_mut)]
        let mut object_2 = object.key("Item").start_object();
        for (key_3, value_4) in var_1 {
            {
                #[allow(unused_mut)]
                let mut object_5 = object_2.key(key_3.as_str()).start_object();
                crate::protocol_serde::shape_attribute_value::ser_attribute_value(
                    &mut object_5,
                    value_4,
                )?;
                object_5.finish();
            }
        }
        object_2.finish();
    }
    if let Some(var_6) = &input.consumed_capacity {
        #[allow(unused_mut)]
        let mut object_7 = object.key("ConsumedCapacity").start_object();
        crate::protocol_serde::shape_consumed_capacity::ser_consumed_capacity(
            &mut object_7,
            var_6,
        )?;
        object_7.finish();
    }
    Ok(())
}
