// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_provisioned_throughput_exceeded_exception_error(
    value: &crate::error::ProvisionedThroughputExceededException,
) -> ::std::result::Result<String, ::aws_smithy_types::error::operation::SerializationError> {
    let mut out = ::std::string::String::new();
    let mut object = ::aws_smithy_json::serialize::JsonObjectWriter::new(&mut out);
    crate::protocol_serde::shape_provisioned_throughput_exceeded_exception::ser_provisioned_throughput_exceeded_exception(&mut object, value)?;
    object
        .key("__type")
        .string("com.amazonaws.dynamodb#ProvisionedThroughputExceededException");
    object.finish();
    Ok(out)
}

pub fn ser_provisioned_throughput_exceeded_exception(
    object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
    input: &crate::error::ProvisionedThroughputExceededException,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    if let Some(var_1) = &input.message {
        object.key("message").string(var_1.as_str());
    }
    Ok(())
}
