// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_billing_mode_summary(
    object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
    input: &crate::model::BillingModeSummary,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    if let Some(var_1) = &input.billing_mode {
        object.key("BillingMode").string(var_1.as_str());
    }
    if let Some(var_2) = &input.last_update_to_pay_per_request_date_time {
        object
            .key("LastUpdateToPayPerRequestDateTime")
            .date_time(var_2, ::aws_smithy_types::date_time::Format::EpochSeconds)?;
    }
    Ok(())
}
