// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_replica_description(
    object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
    input: &crate::model::ReplicaDescription,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    if let Some(var_1) = &input.region_name {
        object.key("RegionName").string(var_1.as_str());
    }
    if let Some(var_2) = &input.replica_status {
        object.key("ReplicaStatus").string(var_2.as_str());
    }
    if let Some(var_3) = &input.replica_status_description {
        object
            .key("ReplicaStatusDescription")
            .string(var_3.as_str());
    }
    if let Some(var_4) = &input.replica_status_percent_progress {
        object
            .key("ReplicaStatusPercentProgress")
            .string(var_4.as_str());
    }
    if let Some(var_5) = &input.kms_master_key_id {
        object.key("KMSMasterKeyId").string(var_5.as_str());
    }
    if let Some(var_6) = &input.provisioned_throughput_override {
        #[allow(unused_mut)]
        let mut object_7 = object.key("ProvisionedThroughputOverride").start_object();
        crate::protocol_serde::shape_provisioned_throughput_override::ser_provisioned_throughput_override(&mut object_7, var_6)?;
        object_7.finish();
    }
    if let Some(var_8) = &input.global_secondary_indexes {
        let mut array_9 = object.key("GlobalSecondaryIndexes").start_array();
        for item_10 in var_8 {
            {
                #[allow(unused_mut)]
                let mut object_11 = array_9.value().start_object();
                crate::protocol_serde::shape_replica_global_secondary_index_description::ser_replica_global_secondary_index_description(&mut object_11, item_10)?;
                object_11.finish();
            }
        }
        array_9.finish();
    }
    if let Some(var_12) = &input.replica_inaccessible_date_time {
        object
            .key("ReplicaInaccessibleDateTime")
            .date_time(var_12, ::aws_smithy_types::date_time::Format::EpochSeconds)?;
    }
    Ok(())
}
