// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_capacity(
                         object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
                         input: &crate::model::Capacity,
                    ) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    if let Some(var_1) = &input.read_capacity_units {
        object.key("ReadCapacityUnits").number(#[allow(clippy::useless_conversion)]::aws_smithy_types::Number::Float((*var_1).into()));
    }
    if let Some(var_2) = &input.write_capacity_units {
        object.key("WriteCapacityUnits").number(#[allow(clippy::useless_conversion)]::aws_smithy_types::Number::Float((*var_2).into()));
    }
    if let Some(var_3) = &input.capacity_units {
        object.key("CapacityUnits").number(#[allow(clippy::useless_conversion)]::aws_smithy_types::Number::Float((*var_3).into()));
    }
    Ok(())
}

