// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_put_item_output_output_output(value: &crate::output::PutItemOutput) -> ::std::result::Result<String, ::aws_smithy_types::error::operation::SerializationError> {
    let mut out = ::std::string::String::new();
                        let mut object = ::aws_smithy_json::serialize::JsonObjectWriter::new(&mut out);
    crate::protocol_serde::shape_put_item_output::ser_put_item_output_output(&mut object, value)?;
    object.finish();
                        Ok(out)
}

pub fn ser_put_item_output_output(
                         object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
                         input: &crate::output::PutItemOutput,
                    ) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    if let Some(var_1) = &input.attributes {
        #[allow(unused_mut)]
        let mut object_2 = object.key("Attributes").start_object();
        for (key_3, value_4) in var_1 {
             {
                #[allow(unused_mut)]
                let mut object_5 = object_2.key(key_3.as_str()).start_object();
                crate::protocol_serde::shape_attribute_value::ser_attribute_value(&mut object_5, value_4)?;
                object_5.finish();
            }
        }
        object_2.finish();
    }
    Ok(())
}

