// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(clippy::unnecessary_wraps)]
pub async fn de_update_item_http_request<B>(
    #[allow(unused_variables)] request: ::http_1x::Request<B>,
) -> std::result::Result<
    crate::input::UpdateItemInput,
    ::aws_smithy_http_server::protocol::aws_json::rejection::RequestRejection,
>
where
    B: ::aws_smithy_http_server::body::HttpBody + Send,
    B::Data: Send,
    ::aws_smithy_http_server::protocol::aws_json::rejection::RequestRejection:
        From<<B as ::aws_smithy_http_server::body::HttpBody>::Error>,
{
    Ok({
        #[allow(unused_mut)]
        let mut input = crate::input::update_item_input::Builder::default();
        #[allow(unused_variables)]
        let ::aws_smithy_runtime_api::http::RequestParts {
            uri, headers, body, ..
        } = ::aws_smithy_runtime_api::http::Request::try_from(request)?.into_parts();
        let bytes = {
            use ::http_body_util::BodyExt;
            body.collect().await?.to_bytes()
        };
        if !bytes.is_empty() {
            ::aws_smithy_http_server::protocol::content_type_header_classifier_smithy(
                &headers,
                Some("application/x-amz-json-1.0"),
            )?;
            input =
                crate::protocol_serde::shape_update_item::de_update_item(bytes.as_ref(), input)?;
        }
        input.build()?
    })
}

#[allow(clippy::unnecessary_wraps)]
pub fn ser_update_item_http_response(
    #[allow(unused_variables)] output: crate::output::UpdateItemOutput,
) -> std::result::Result<
    ::aws_smithy_http_server::response::Response,
    ::aws_smithy_http_server::protocol::aws_json::rejection::ResponseRejection,
> {
    Ok({
        #[allow(unused_mut)]
        let mut builder = ::http_1x::Response::builder();
        builder = ::aws_smithy_http::header::set_response_header_if_absent(
            builder,
            ::http_1x::header::CONTENT_TYPE,
            "application/x-amz-json-1.0",
        );
        let http_status: u16 = 200;
        builder = builder.status(http_status);
        let payload =
            crate::protocol_serde::shape_update_item_output::ser_update_item_output_output_output(
                &output,
            )?;
        let content_length = payload.len();
        builder = ::aws_smithy_http::header::set_response_header_if_absent(
            builder,
            ::http_1x::header::CONTENT_LENGTH,
            content_length,
        );
        let body = ::aws_smithy_http_server::body::to_boxed(payload);
        builder.body(body)?
    })
}

#[allow(clippy::unnecessary_wraps)]
pub fn ser_update_item_http_error(
    error: &crate::error::UpdateItemError,
) -> std::result::Result<
    ::aws_smithy_http_server::response::Response,
    ::aws_smithy_http_server::protocol::aws_json::rejection::ResponseRejection,
> {
    Ok({
        match error {
            crate::error::UpdateItemError::ValidationException(output) => {
                let payload = crate::protocol_serde::shape_validation_exception::ser_validation_exception_error(output)?;
                #[allow(unused_mut)]
                let mut builder = ::http_1x::Response::builder();
                builder = ::aws_smithy_http::header::set_response_header_if_absent(
                    builder,
                    ::http_1x::header::CONTENT_TYPE,
                    "application/x-amz-json-1.0",
                );
                let content_length = payload.len();
                builder = ::aws_smithy_http::header::set_response_header_if_absent(
                    builder,
                    ::http_1x::header::CONTENT_LENGTH,
                    content_length,
                );
                builder
                    .status(400)
                    .body(::aws_smithy_http_server::body::to_boxed(payload))?
            }
            crate::error::UpdateItemError::ConditionalCheckFailedException(output) => {
                let payload = crate::protocol_serde::shape_conditional_check_failed_exception::ser_conditional_check_failed_exception_error(output)?;
                #[allow(unused_mut)]
                let mut builder = ::http_1x::Response::builder();
                builder = ::aws_smithy_http::header::set_response_header_if_absent(
                    builder,
                    ::http_1x::header::CONTENT_TYPE,
                    "application/x-amz-json-1.0",
                );
                let content_length = payload.len();
                builder = ::aws_smithy_http::header::set_response_header_if_absent(
                    builder,
                    ::http_1x::header::CONTENT_LENGTH,
                    content_length,
                );
                builder
                    .status(400)
                    .body(::aws_smithy_http_server::body::to_boxed(payload))?
            }
            crate::error::UpdateItemError::InternalServerError(output) => {
                let payload = crate::protocol_serde::shape_internal_server_error::ser_internal_server_error_error(output)?;
                #[allow(unused_mut)]
                let mut builder = ::http_1x::Response::builder();
                builder = ::aws_smithy_http::header::set_response_header_if_absent(
                    builder,
                    ::http_1x::header::CONTENT_TYPE,
                    "application/x-amz-json-1.0",
                );
                let content_length = payload.len();
                builder = ::aws_smithy_http::header::set_response_header_if_absent(
                    builder,
                    ::http_1x::header::CONTENT_LENGTH,
                    content_length,
                );
                builder
                    .status(500)
                    .body(::aws_smithy_http_server::body::to_boxed(payload))?
            }
            crate::error::UpdateItemError::InvalidEndpointException(output) => {
                let payload = crate::protocol_serde::shape_invalid_endpoint_exception::ser_invalid_endpoint_exception_error(output)?;
                #[allow(unused_mut)]
                let mut builder = ::http_1x::Response::builder();
                builder = ::aws_smithy_http::header::set_response_header_if_absent(
                    builder,
                    ::http_1x::header::CONTENT_TYPE,
                    "application/x-amz-json-1.0",
                );
                let content_length = payload.len();
                builder = ::aws_smithy_http::header::set_response_header_if_absent(
                    builder,
                    ::http_1x::header::CONTENT_LENGTH,
                    content_length,
                );
                builder
                    .status(400)
                    .body(::aws_smithy_http_server::body::to_boxed(payload))?
            }
            crate::error::UpdateItemError::ItemCollectionSizeLimitExceededException(output) => {
                let payload = crate::protocol_serde::shape_item_collection_size_limit_exceeded_exception::ser_item_collection_size_limit_exceeded_exception_error(output)?;
                #[allow(unused_mut)]
                let mut builder = ::http_1x::Response::builder();
                builder = ::aws_smithy_http::header::set_response_header_if_absent(
                    builder,
                    ::http_1x::header::CONTENT_TYPE,
                    "application/x-amz-json-1.0",
                );
                let content_length = payload.len();
                builder = ::aws_smithy_http::header::set_response_header_if_absent(
                    builder,
                    ::http_1x::header::CONTENT_LENGTH,
                    content_length,
                );
                builder
                    .status(400)
                    .body(::aws_smithy_http_server::body::to_boxed(payload))?
            }
            crate::error::UpdateItemError::ProvisionedThroughputExceededException(output) => {
                let payload = crate::protocol_serde::shape_provisioned_throughput_exceeded_exception::ser_provisioned_throughput_exceeded_exception_error(output)?;
                #[allow(unused_mut)]
                let mut builder = ::http_1x::Response::builder();
                builder = ::aws_smithy_http::header::set_response_header_if_absent(
                    builder,
                    ::http_1x::header::CONTENT_TYPE,
                    "application/x-amz-json-1.0",
                );
                let content_length = payload.len();
                builder = ::aws_smithy_http::header::set_response_header_if_absent(
                    builder,
                    ::http_1x::header::CONTENT_LENGTH,
                    content_length,
                );
                builder
                    .status(400)
                    .body(::aws_smithy_http_server::body::to_boxed(payload))?
            }
            crate::error::UpdateItemError::RequestLimitExceeded(output) => {
                let payload = crate::protocol_serde::shape_request_limit_exceeded::ser_request_limit_exceeded_error(output)?;
                #[allow(unused_mut)]
                let mut builder = ::http_1x::Response::builder();
                builder = ::aws_smithy_http::header::set_response_header_if_absent(
                    builder,
                    ::http_1x::header::CONTENT_TYPE,
                    "application/x-amz-json-1.0",
                );
                let content_length = payload.len();
                builder = ::aws_smithy_http::header::set_response_header_if_absent(
                    builder,
                    ::http_1x::header::CONTENT_LENGTH,
                    content_length,
                );
                builder
                    .status(400)
                    .body(::aws_smithy_http_server::body::to_boxed(payload))?
            }
            crate::error::UpdateItemError::ResourceNotFoundException(output) => {
                let payload = crate::protocol_serde::shape_resource_not_found_exception::ser_resource_not_found_exception_error(output)?;
                #[allow(unused_mut)]
                let mut builder = ::http_1x::Response::builder();
                builder = ::aws_smithy_http::header::set_response_header_if_absent(
                    builder,
                    ::http_1x::header::CONTENT_TYPE,
                    "application/x-amz-json-1.0",
                );
                let content_length = payload.len();
                builder = ::aws_smithy_http::header::set_response_header_if_absent(
                    builder,
                    ::http_1x::header::CONTENT_LENGTH,
                    content_length,
                );
                builder
                    .status(400)
                    .body(::aws_smithy_http_server::body::to_boxed(payload))?
            }
            crate::error::UpdateItemError::TransactionConflictException(output) => {
                let payload = crate::protocol_serde::shape_transaction_conflict_exception::ser_transaction_conflict_exception_error(output)?;
                #[allow(unused_mut)]
                let mut builder = ::http_1x::Response::builder();
                builder = ::aws_smithy_http::header::set_response_header_if_absent(
                    builder,
                    ::http_1x::header::CONTENT_TYPE,
                    "application/x-amz-json-1.0",
                );
                let content_length = payload.len();
                builder = ::aws_smithy_http::header::set_response_header_if_absent(
                    builder,
                    ::http_1x::header::CONTENT_LENGTH,
                    content_length,
                );
                builder
                    .status(400)
                    .body(::aws_smithy_http_server::body::to_boxed(payload))?
            }
        }
    })
}

pub(crate) fn de_update_item(
    _value: &[u8],
    mut builder: crate::input::update_item_input::Builder,
) -> ::std::result::Result<
    crate::input::update_item_input::Builder,
    ::aws_smithy_json::deserialize::error::DeserializeError,
> {
    let mut tokens_owned = ::aws_smithy_json::deserialize::json_token_iter(
        crate::protocol_serde::or_empty_doc(_value),
    )
    .peekable();
    let tokens = &mut tokens_owned;
    ::aws_smithy_json::deserialize::token::expect_start_object(tokens.next())?;
    loop {
        match tokens.next().transpose()? {
            Some(::aws_smithy_json::deserialize::Token::EndObject { .. }) => break,
            Some(::aws_smithy_json::deserialize::Token::ObjectKey { key, .. }) => {
                match key.to_unescaped()?.as_ref() {
                    "TableName" => {
                        if let Some(v) =
                            ::aws_smithy_json::deserialize::token::expect_string_or_null(
                                tokens.next(),
                            )?
                            .map(|s| s.to_unescaped().map(|u| u.into_owned()))
                            .transpose()?
                        {
                            builder = builder.set_table_name(v);
                        }
                    }
                    "Key" => {
                        if let Some(v) = crate::protocol_serde::shape_key::de_key(tokens, _value)? {
                            builder = builder.set_key(v);
                        }
                    }
                    "AttributeUpdates" => {
                        builder = builder.set_attribute_updates(
                            crate::protocol_serde::shape_attribute_updates::de_attribute_updates(
                                tokens, _value,
                            )?,
                        );
                    }
                    "Expected" => {
                        builder = builder.set_expected(
                            crate::protocol_serde::shape_expected_attribute_map::de_expected_attribute_map(tokens, _value)?
                        );
                    }
                    "ConditionalOperator" => {
                        builder = builder.set_conditional_operator(
                            ::aws_smithy_json::deserialize::token::expect_string_or_null(
                                tokens.next(),
                            )?
                            .map(|s| s.to_unescaped().map(|u| u.into_owned()))
                            .transpose()?,
                        );
                    }
                    "ReturnValues" => {
                        builder = builder.set_return_values(
                            ::aws_smithy_json::deserialize::token::expect_string_or_null(
                                tokens.next(),
                            )?
                            .map(|s| s.to_unescaped().map(|u| u.into_owned()))
                            .transpose()?,
                        );
                    }
                    "ReturnConsumedCapacity" => {
                        builder = builder.set_return_consumed_capacity(
                            ::aws_smithy_json::deserialize::token::expect_string_or_null(
                                tokens.next(),
                            )?
                            .map(|s| s.to_unescaped().map(|u| u.into_owned()))
                            .transpose()?,
                        );
                    }
                    "ReturnItemCollectionMetrics" => {
                        builder = builder.set_return_item_collection_metrics(
                            ::aws_smithy_json::deserialize::token::expect_string_or_null(
                                tokens.next(),
                            )?
                            .map(|s| s.to_unescaped().map(|u| u.into_owned()))
                            .transpose()?,
                        );
                    }
                    "UpdateExpression" => {
                        builder = builder.set_update_expression(
                            ::aws_smithy_json::deserialize::token::expect_string_or_null(
                                tokens.next(),
                            )?
                            .map(|s| s.to_unescaped().map(|u| u.into_owned()))
                            .transpose()?,
                        );
                    }
                    "ConditionExpression" => {
                        builder = builder.set_condition_expression(
                            ::aws_smithy_json::deserialize::token::expect_string_or_null(
                                tokens.next(),
                            )?
                            .map(|s| s.to_unescaped().map(|u| u.into_owned()))
                            .transpose()?,
                        );
                    }
                    "ExpressionAttributeNames" => {
                        builder = builder.set_expression_attribute_names(
                            crate::protocol_serde::shape_expression_attribute_name_map::de_expression_attribute_name_map(tokens, _value)?
                        );
                    }
                    "ExpressionAttributeValues" => {
                        builder = builder.set_expression_attribute_values(
                            crate::protocol_serde::shape_expression_attribute_value_map::de_expression_attribute_value_map(tokens, _value)?
                        );
                    }
                    _ => ::aws_smithy_json::deserialize::token::skip_value(tokens)?,
                }
            }
            other => {
                return Err(
                    ::aws_smithy_json::deserialize::error::DeserializeError::custom(format!(
                        "expected object key or end object, found: {other:?}"
                    )),
                )
            }
        }
    }
    if tokens.next().is_some() {
        return Err(
            ::aws_smithy_json::deserialize::error::DeserializeError::custom(
                "found more JSON tokens after completing parsing",
            ),
        );
    }
    Ok(builder)
}
