// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_sse_description(
    object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
    input: &crate::model::SseDescription,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    if let Some(var_1) = &input.status {
        object.key("Status").string(var_1.as_str());
    }
    if let Some(var_2) = &input.sse_type {
        object.key("SSEType").string(var_2.as_str());
    }
    if let Some(var_3) = &input.kms_master_key_arn {
        object.key("KMSMasterKeyArn").string(var_3.as_str());
    }
    if let Some(var_4) = &input.inaccessible_encryption_date_time {
        object
            .key("InaccessibleEncryptionDateTime")
            .date_time(var_4, ::aws_smithy_types::date_time::Format::EpochSeconds)?;
    }
    Ok(())
}
