// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub(crate) fn de_attribute_updates<'a, I>(
    tokens: &mut ::std::iter::Peekable<I>,
    _value: &'a [u8],
) -> ::std::result::Result<
    Option<crate::unconstrained::attribute_updates_unconstrained::AttributeUpdatesUnconstrained>,
    ::aws_smithy_json::deserialize::error::DeserializeError,
>
where
    I: Iterator<
        Item = Result<
            ::aws_smithy_json::deserialize::Token<'a>,
            ::aws_smithy_json::deserialize::error::DeserializeError,
        >,
    >,
{
    match tokens.next().transpose()? {
        Some(::aws_smithy_json::deserialize::Token::ValueNull { .. }) => Ok(None),
        Some(::aws_smithy_json::deserialize::Token::StartObject { .. }) => {
            let mut map = ::std::collections::HashMap::new();
            loop {
                match tokens.next().transpose()? {
                    Some(::aws_smithy_json::deserialize::Token::EndObject { .. }) => break,
                    Some(::aws_smithy_json::deserialize::Token::ObjectKey { key, .. }) => {
                        let key = key.to_unescaped().map(|u| u.into_owned())?;
                        let value =
                            crate::protocol_serde::shape_attribute_value_update::de_attribute_value_update(tokens, _value)?
                        ;
                        match value {
                            Some(value) => {
                                map.insert(key, value);
                            }
                            None => {
                                return Err(
                                    ::aws_smithy_json::deserialize::error::DeserializeError::custom(
                                        "dense map cannot contain null values",
                                    ),
                                )
                            }
                        }
                    }
                    other => {
                        return Err(
                            ::aws_smithy_json::deserialize::error::DeserializeError::custom(
                                format!("expected object key or end object, found: {other:?}"),
                            ),
                        )
                    }
                }
            }
            Ok(Some(crate::unconstrained::attribute_updates_unconstrained::AttributeUpdatesUnconstrained(map)))
        }
        _ => Err(
            ::aws_smithy_json::deserialize::error::DeserializeError::custom(
                "expected start object or null",
            ),
        ),
    }
}
