// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_consumed_capacity(
                         object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
                         input: &crate::model::ConsumedCapacity,
                    ) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    if let Some(var_1) = &input.table_name {
        object.key("TableName").string(var_1.as_str());
    }
    if let Some(var_2) = &input.capacity_units {
        object.key("CapacityUnits").number(#[allow(clippy::useless_conversion)]::aws_smithy_types::Number::Float((*var_2).into()));
    }
    if let Some(var_3) = &input.read_capacity_units {
        object.key("ReadCapacityUnits").number(#[allow(clippy::useless_conversion)]::aws_smithy_types::Number::Float((*var_3).into()));
    }
    if let Some(var_4) = &input.write_capacity_units {
        object.key("WriteCapacityUnits").number(#[allow(clippy::useless_conversion)]::aws_smithy_types::Number::Float((*var_4).into()));
    }
    if let Some(var_5) = &input.table {
        #[allow(unused_mut)]
        let mut object_6 = object.key("Table").start_object();
        crate::protocol_serde::shape_capacity::ser_capacity(&mut object_6, var_5)?;
        object_6.finish();
    }
    if let Some(var_7) = &input.local_secondary_indexes {
        #[allow(unused_mut)]
        let mut object_8 = object.key("LocalSecondaryIndexes").start_object();
        for (key_9, value_10) in var_7 {
             {
                #[allow(unused_mut)]
                let mut object_11 = object_8.key(key_9.as_str()).start_object();
                crate::protocol_serde::shape_capacity::ser_capacity(&mut object_11, value_10)?;
                object_11.finish();
            }
        }
        object_8.finish();
    }
    if let Some(var_12) = &input.global_secondary_indexes {
        #[allow(unused_mut)]
        let mut object_13 = object.key("GlobalSecondaryIndexes").start_object();
        for (key_14, value_15) in var_12 {
             {
                #[allow(unused_mut)]
                let mut object_16 = object_13.key(key_14.as_str()).start_object();
                crate::protocol_serde::shape_capacity::ser_capacity(&mut object_16, value_15)?;
                object_16.finish();
            }
        }
        object_13.finish();
    }
    Ok(())
}

