// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub(crate) fn de_global_secondary_index<'a, I>(tokens: &mut ::std::iter::Peekable<I>, _value: &'a [u8]) -> ::std::result::Result<Option<crate::model::global_secondary_index::Builder>, ::aws_smithy_json::deserialize::error::DeserializeError>
                        where I: Iterator<Item = Result<::aws_smithy_json::deserialize::Token<'a>, ::aws_smithy_json::deserialize::error::DeserializeError>> {
    match tokens.next().transpose()? {
        Some(::aws_smithy_json::deserialize::Token::ValueNull { .. }) => Ok(None),
                        Some(::aws_smithy_json::deserialize::Token::StartObject { .. }) => {
            #[allow(unused_mut)]
            let mut builder = crate::model::global_secondary_index::Builder::default();
            loop {
                match tokens.next().transpose()? {
                    Some(::aws_smithy_json::deserialize::Token::EndObject { .. }) => break,
                                            Some(::aws_smithy_json::deserialize::Token::ObjectKey { key, .. }) => {
                        match key.to_unescaped()?.as_ref() {
                            "IndexName" => {
                                if let Some(v) =
                                ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
                                    s.to_unescaped().map(|u|
                                        u.into_owned()
                                    )
                                ).transpose()?
                                {
                                                                            builder = builder.set_index_name(v);
                                                                        }
                            }
                            "KeySchema" => {
                                if let Some(v) =
                                crate::protocol_serde::shape_key_schema::de_key_schema(tokens, _value)?
                                {
                                                                            builder = builder.set_key_schema(v);
                                                                        }
                            }
                            "Projection" => {
                                if let Some(v) =
                                crate::protocol_serde::shape_projection::de_projection(tokens, _value)?
                                {
                                                                            builder = builder.set_projection(v);
                                                                        }
                            }
                            "ProvisionedThroughput" => {
                                builder = builder.set_provisioned_throughput(
                                    crate::protocol_serde::shape_provisioned_throughput::de_provisioned_throughput(tokens, _value)?
                                );
                            }
                            _ => ::aws_smithy_json::deserialize::token::skip_value(tokens)?
                        }
                    }
                    other => return Err(::aws_smithy_json::deserialize::error::DeserializeError::custom(format!("expected object key or end object, found: {other:?}")))
                }
            }
            Ok(Some(builder))
        }
        _ => {
            Err(::aws_smithy_json::deserialize::error::DeserializeError::custom("expected start object or null"))
        }
    }
}

