// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_global_secondary_index_description(
    object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
    input: &crate::model::GlobalSecondaryIndexDescription,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    if let Some(var_1) = &input.index_name {
        object.key("IndexName").string(var_1.as_str());
    }
    if let Some(var_2) = &input.key_schema {
        let mut array_3 = object.key("KeySchema").start_array();
        for item_4 in var_2 {
            {
                #[allow(unused_mut)]
                let mut object_5 = array_3.value().start_object();
                crate::protocol_serde::shape_key_schema_element::ser_key_schema_element(
                    &mut object_5,
                    item_4,
                )?;
                object_5.finish();
            }
        }
        array_3.finish();
    }
    if let Some(var_6) = &input.projection {
        #[allow(unused_mut)]
        let mut object_7 = object.key("Projection").start_object();
        crate::protocol_serde::shape_projection::ser_projection(&mut object_7, var_6)?;
        object_7.finish();
    }
    if let Some(var_8) = &input.index_status {
        object.key("IndexStatus").string(var_8.as_str());
    }
    if let Some(var_9) = &input.backfilling {
        object.key("Backfilling").boolean(*var_9);
    }
    if let Some(var_10) = &input.provisioned_throughput {
        #[allow(unused_mut)]
        let mut object_11 = object.key("ProvisionedThroughput").start_object();
        crate::protocol_serde::shape_provisioned_throughput_description::ser_provisioned_throughput_description(&mut object_11, var_10)?;
        object_11.finish();
    }
    if let Some(var_12) = &input.index_size_bytes {
        object.key("IndexSizeBytes").number(
            #[allow(clippy::useless_conversion)]
            ::aws_smithy_types::Number::NegInt((*var_12).into()),
        );
    }
    if let Some(var_13) = &input.item_count {
        object.key("ItemCount").number(
            #[allow(clippy::useless_conversion)]
            ::aws_smithy_types::Number::NegInt((*var_13).into()),
        );
    }
    if let Some(var_14) = &input.index_arn {
        object.key("IndexArn").string(var_14.as_str());
    }
    Ok(())
}
