// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(clippy::unnecessary_wraps)]
pub async fn de_get_item_http_request<B>(
    #[allow(unused_variables)] request: ::http::Request<B>
) -> std::result::Result<
    crate::input::GetItemInput,
    ::aws_smithy_http_server::protocol::aws_json::rejection::RequestRejection
>
where
    B: ::aws_smithy_http_server::body::HttpBody + Send, 
    B::Data: Send,
    ::aws_smithy_http_server::protocol::aws_json::rejection::RequestRejection: From<<B as ::aws_smithy_http_server::body::HttpBody>::Error> {
    Ok({
        #[allow(unused_mut)]
        let mut input = crate::input::get_item_input::Builder::default();
        #[allow(unused_variables)]
        let ::aws_smithy_runtime_api::http::RequestParts { uri, headers, body, .. } = ::aws_smithy_runtime_api::http::Request::try_from(request)?.into_parts();
        let bytes = ::hyper::body::to_bytes(body).await?;
        if !bytes.is_empty() {
            ::aws_smithy_http_server::protocol::content_type_header_classifier_smithy(
                                    &headers,
                                    Some("application/x-amz-json-1.0"),
                                )?;
                                input = crate::protocol_serde::shape_get_item::de_get_item(bytes.as_ref(), input)?;
        }
        input.build()?
    })
}

#[allow(clippy::unnecessary_wraps)]
pub fn ser_get_item_http_response(
    #[allow(unused_variables)] output: crate::output::GetItemOutput
) -> std::result::Result<
    ::aws_smithy_http_server::response::Response,
    ::aws_smithy_http_server::protocol::aws_json::rejection::ResponseRejection
> {
    Ok({
        #[allow(unused_mut)]
        let mut builder = ::http::Response::builder();
        builder = ::aws_smithy_http::header::set_response_header_if_absent(
                        builder,
                        ::http::header::CONTENT_TYPE,
                        "application/x-amz-json-1.0",
                    );
        let http_status: u16 = 200;
                        builder = builder.status(http_status);
        let payload =
            crate::protocol_serde::shape_get_item_output::ser_get_item_output_output_output(&output)?
        ;
        let content_length = payload.len();
                    builder = ::aws_smithy_http::header::set_response_header_if_absent(builder, ::http::header::CONTENT_LENGTH, content_length);
        let body = ::aws_smithy_http_server::body::to_boxed(payload);
        builder.body(body)?
    })
}

#[allow(clippy::unnecessary_wraps)]
pub fn ser_get_item_http_error(error: &crate::error::GetItemError) -> std::result::Result<::aws_smithy_http_server::response::Response, ::aws_smithy_http_server::protocol::aws_json::rejection::ResponseRejection> {
    Ok({
        match error {
            crate::error::GetItemError::ValidationException(output) => {
                let payload = crate::protocol_serde::shape_validation_exception::ser_validation_exception_error(output)?;
                #[allow(unused_mut)]
                let mut builder = ::http::Response::builder();
                builder = ::aws_smithy_http::header::set_response_header_if_absent(
                                builder,
                                ::http::header::CONTENT_TYPE,
                                "application/x-amz-json-1.0",
                            );
                let content_length = payload.len();
                            builder = ::aws_smithy_http::header::set_response_header_if_absent(builder, ::http::header::CONTENT_LENGTH, content_length);
                builder.status(400).body(::aws_smithy_http_server::body::to_boxed(payload))?
            }
            crate::error::GetItemError::InternalServerError(output) => {
                let payload = crate::protocol_serde::shape_internal_server_error::ser_internal_server_error_error(output)?;
                #[allow(unused_mut)]
                let mut builder = ::http::Response::builder();
                builder = ::aws_smithy_http::header::set_response_header_if_absent(
                                builder,
                                ::http::header::CONTENT_TYPE,
                                "application/x-amz-json-1.0",
                            );
                let content_length = payload.len();
                            builder = ::aws_smithy_http::header::set_response_header_if_absent(builder, ::http::header::CONTENT_LENGTH, content_length);
                builder.status(500).body(::aws_smithy_http_server::body::to_boxed(payload))?
            }
            crate::error::GetItemError::ProvisionedThroughputExceededException(output) => {
                let payload = crate::protocol_serde::shape_provisioned_throughput_exceeded_exception::ser_provisioned_throughput_exceeded_exception_error(output)?;
                #[allow(unused_mut)]
                let mut builder = ::http::Response::builder();
                builder = ::aws_smithy_http::header::set_response_header_if_absent(
                                builder,
                                ::http::header::CONTENT_TYPE,
                                "application/x-amz-json-1.0",
                            );
                let content_length = payload.len();
                            builder = ::aws_smithy_http::header::set_response_header_if_absent(builder, ::http::header::CONTENT_LENGTH, content_length);
                builder.status(400).body(::aws_smithy_http_server::body::to_boxed(payload))?
            }
            crate::error::GetItemError::ResourceNotFoundException(output) => {
                let payload = crate::protocol_serde::shape_resource_not_found_exception::ser_resource_not_found_exception_error(output)?;
                #[allow(unused_mut)]
                let mut builder = ::http::Response::builder();
                builder = ::aws_smithy_http::header::set_response_header_if_absent(
                                builder,
                                ::http::header::CONTENT_TYPE,
                                "application/x-amz-json-1.0",
                            );
                let content_length = payload.len();
                            builder = ::aws_smithy_http::header::set_response_header_if_absent(builder, ::http::header::CONTENT_LENGTH, content_length);
                builder.status(400).body(::aws_smithy_http_server::body::to_boxed(payload))?
            }
        }
    })
}

pub(crate) fn de_get_item(value: &[u8], mut builder: crate::input::get_item_input::Builder) -> ::std::result::Result<crate::input::get_item_input::Builder, ::aws_smithy_json::deserialize::error::DeserializeError> {
    let mut tokens_owned = ::aws_smithy_json::deserialize::json_token_iter(crate::protocol_serde::or_empty_doc(value)).peekable();
                        let tokens = &mut tokens_owned;
                        ::aws_smithy_json::deserialize::token::expect_start_object(tokens.next())?;
    loop {
        match tokens.next().transpose()? {
            Some(::aws_smithy_json::deserialize::Token::EndObject { .. }) => break,
                                    Some(::aws_smithy_json::deserialize::Token::ObjectKey { key, .. }) => {
                match key.to_unescaped()?.as_ref() {
                    "TableName" => {
                        if let Some(v) =
                        ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
                            s.to_unescaped().map(|u|
                                u.into_owned()
                            )
                        ).transpose()?
                        {
                                                                    builder = builder.set_table_name(v);
                                                                }
                    }
                    "Key" => {
                        if let Some(v) =
                        crate::protocol_serde::shape_key::de_key(tokens)?
                        {
                                                                    builder = builder.set_key(v);
                                                                }
                    }
                    "ConsistentRead" => {
                        builder = builder.set_consistent_read(
                            ::aws_smithy_json::deserialize::token::expect_bool_or_null(tokens.next())?
                        );
                    }
                    "ProjectionExpression" => {
                        builder = builder.set_projection_expression(
                            ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
                                s.to_unescaped().map(|u|
                                    u.into_owned()
                                )
                            ).transpose()?
                        );
                    }
                    "ExpressionAttributeNames" => {
                        builder = builder.set_expression_attribute_names(
                            crate::protocol_serde::shape_expression_attribute_name_map::de_expression_attribute_name_map(tokens)?
                        );
                    }
                    _ => ::aws_smithy_json::deserialize::token::skip_value(tokens)?
                }
            }
            other => return Err(::aws_smithy_json::deserialize::error::DeserializeError::custom(format!("expected object key or end object, found: {:?}", other)))
        }
    }
    if tokens.next().is_some() {
        return Err(::aws_smithy_json::deserialize::error::DeserializeError::custom("found more JSON tokens after completing parsing"));
    }
    Ok(builder)
}

