// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub(crate) fn de_provisioned_throughput<'a, I>(tokens: &mut ::std::iter::Peekable<I>) -> ::std::result::Result<Option<crate::model::provisioned_throughput::Builder>, ::aws_smithy_json::deserialize::error::DeserializeError>
                        where I: Iterator<Item = Result<::aws_smithy_json::deserialize::Token<'a>, ::aws_smithy_json::deserialize::error::DeserializeError>> {
    match tokens.next().transpose()? {
        Some(::aws_smithy_json::deserialize::Token::ValueNull { .. }) => Ok(None),
                        Some(::aws_smithy_json::deserialize::Token::StartObject { .. }) => {
            #[allow(unused_mut)]
            let mut builder = crate::model::provisioned_throughput::Builder::default();
            loop {
                match tokens.next().transpose()? {
                    Some(::aws_smithy_json::deserialize::Token::EndObject { .. }) => break,
                                            Some(::aws_smithy_json::deserialize::Token::ObjectKey { key, .. }) => {
                        match key.to_unescaped()?.as_ref() {
                            "ReadCapacityUnits" => {
                                if let Some(v) =
                                ::aws_smithy_json::deserialize::token::expect_number_or_null(tokens.next())?
                                                    .map(i64::try_from)
                                                    .transpose()?
                                {
                                                                            builder = builder.set_read_capacity_units(v);
                                                                        }
                            }
                            "WriteCapacityUnits" => {
                                if let Some(v) =
                                ::aws_smithy_json::deserialize::token::expect_number_or_null(tokens.next())?
                                                    .map(i64::try_from)
                                                    .transpose()?
                                {
                                                                            builder = builder.set_write_capacity_units(v);
                                                                        }
                            }
                            _ => ::aws_smithy_json::deserialize::token::skip_value(tokens)?
                        }
                    }
                    other => return Err(::aws_smithy_json::deserialize::error::DeserializeError::custom(format!("expected object key or end object, found: {:?}", other)))
                }
            }
            Ok(Some(builder))
        }
        _ => {
            Err(::aws_smithy_json::deserialize::error::DeserializeError::custom("expected start object or null"))
        }
    }
}

